<?php

/************************************************************************
Class: Config.php
Creation: 05/11/2013
Creator: Marcus Siqueira
Dependencies:

Description: 
			Classe de configurcão Web Base.
			Padroes: Singleton.
Functions: 
			public static function GetDefaultLanguageByDir($PageDirName);
			public static function GetPageConstant($Constant);
			public function SetApplication();
**************************************************************************/
if (!class_exists("Factory"))
{
	if(file_exists(BASE_PATH_PHP_CONTROLLER . "Factory.php"))
		include_once(BASE_PATH_PHP_CONTROLLER . "Factory.php");
	else exit(basename(__FILE__, '.php') . ': Error Loading Base Class Factory');
}

class Config
{
	const PARAMETERS_NULL                                               = "ParametersNull";
	const POST_IS_NULL                                                  = "PostIsNull";
	const SUCCESS                                                       = "Success";
	const SESSION_IS_NULL                                               = "SessionIsNUll";
	
	/* Constantes gerais usadas pelo site */
	const CHECKBOX_CHECKED                                              = "checked";
	const CHECKBOX_UNCHECKED                                            = "";
	const DIV_RETURN                                                    = "DivReturn";
	const ENABLED                                                       = "Enabled";
	const EXCEPTION_ASSOC_TICKET_USER_REQUESTING_TICKET                 = "ExceptionAssocTicketUserRequestingTicket";
	const EXCEPTION_ASSOC_TICKET_USER_REQUESTING_TYPE                   = "ExceptionAssocTicketUserRequestingType";
	const EXCEPTION_ASSOC_TICKET_USER_REQUESTING_USER                   = "ExceptionAssocTicketUserRequestingUser";
	const EXCEPTION_ASSOC_USER_TEAM_TEAM                                = "ExceptionAssocUserTeamTeam";
	const EXCEPTION_ASSOC_USER_TEAM_TYPE                                = "ExceptionAssocUserTeamType";
	const EXCEPTION_ASSOC_USER_TEAM_USER                                = "ExceptionAssocUserTeamUser";
	const EXCEPTION_CORPORATION                                         = "ExceptionCorporation";
	const EXCEPTION_CORPORATION_ACTIVE                                  = "ExceotionCorporationActive";
	const EXCEPTION_CORPORATION_NAME                                    = "ExceptionCorporationName";
	const EXCEPTION_COUNTRY_ABBREVIATION                                = "ExceptionCountryAbbreviation";
	const EXCEPTION_COUNTRY_NAME                                        = "ExceptionCountryName";
	const EXCEPTION_DEPARTMENT_DEPARTMENT_CORPORATION                   = "ExceptionDepartmentDepartmentCorporation";
	const EXCEPTION_DEPARTMENT_DEPARTMENT_NAME                          = "ExceptionDepartmentDepartmentName";
	const EXCEPTION_HISTORY_TICKET_DESCRIPTION                          = "ExceptionHistoryTicketDescription";
	const EXCEPTION_HISTORY_TICKET_ID                                   = "ExceptionHistoryTicketId";
	const EXCEPTION_HISTORY_TICKET_STATUS                               = "ExceptionHistoryTicketStatus";
	const EXCEPTION_HISTORY_TICKET_TICKET_ID                            = "ExceptionHistoryTicketTicketId";
	const EXCEPTION_HISTORY_TICKET_TITLE                                = "ExceptionHistoryTicketTitle";
	const EXCEPTION_HISTORY_TICKET_TYPE                                 = "ExceptionHistoryTicketType";
	const EXCEPTION_NOTIFICATION_ACTIVE                                 = "ExceptionNotificationActive";
	const EXCEPTION_NOTIFICATION_ID                                     = "ExceptionNotificationId";
	const EXCEPTION_NOTIFICATION_TEXT                                   = "ExceptionNotificationText";
	const EXCEPTION_REGISTER_DATE                                       = "ExceptionRegisterDate";
	const EXCEPTION_SYSTEM_CONFIGURATION_OPTION_ACTIVE                  = "ExceptionSystemConfigurationOptionActive";
	const EXCEPTION_SYSTEM_CONFIGURATION_OPTION_DESCRIPTION             = "ExceptionSystemConfigurationOptionDescription";
	const EXCEPTION_SYSTEM_CONFIGURATION_OPTION_NAME                    = "ExceptionSystemConfigurationOptionName";
	const EXCEPTION_SYSTEM_CONFIGURATION_OPTION_NUMBER                  = "ExceptionSystemConfigurationOptionNumber";
	const EXCEPTION_TEAM_DESCRIPTION                                    = "ExceptionTeamDescription";
	const EXCEPTION_TEAM_ID                                             = "ExceptionTeamId";
	const EXCEPTION_TEAM_NAME                                           = "ExceptionTeamName";
	const EXCEPTION_TICKET_DESCRIPTION                                  = "ExceptionTicketDescription";
	const EXCEPTION_TICKET_ID                                           = "ExceptionTicketId";
	const EXCEPTION_TICKET_STATUS                                       = "ExceptionTicketStatus";
	const EXCEPTION_TICKET_TITLE                                        = "ExceptionTicketTitle";
	const EXCEPTION_TICKET_TYPE                                         = "ExceptionTicketType";
	const EXCEPTION_TYPE_ASSOC_USER_TEAM_DESCRIPTION                    = "ExceptionTypeAssocUserTeamDescription";
	const EXCEPTION_TYPE_ASSOC_USER_TEAM_ID                             = "ExceptionTypeAssocUserTeamId";
	const EXCEPTION_TYPE_TICKET_DESCRIPTION                             = "ExeceptionTypeTicketTypeTicketDescription";
	const EXCEPTION_TYPE_STATUS_TICKET_DESCRIPTION                      = "ExceptionTypeStatusTicketDescription";
	const EXCEPTION_TYPE_USER_DESCRIPTION                               = "ExceptionTypeUserDescription";
	const EXCEPTION_USER                                                = "ExceptionUser";
	const EXCEPTION_USER_ACTIVE                                         = "ExceptionUserActive";
	const EXCEPTION_USER_BIRTH_DATE                                     = "ExceptionUserBirthDate";
	const EXCEPTION_USER_CONFIRMED                                      = "ExceptionUserConfirmed";
	const EXCEPTION_USER_COUNTRY                                        = "ExceptionUserCountry";
	const EXCEPTION_USER_EMAIL                                          = "ExceptionUserEmail";
	const EXCEPTION_USER_GENDER                                         = "ExceptionUserGender";
	const EXCEPTION_USER_HASH_CODE                                      = "ExceptionUserHashCode";
	const EXCEPTION_USER_NAME                                           = "ExceptionUserName";
	const EXCEPTION_USER_SESSION_EXPIRES                                = "ExceptionUserSessionExpires";
	const EXCEPTION_USER_TYPE                                           = "ExceptionUserType";
	const EXCEPTION_USER_TWO_STEP_VERIFICATION                          = "ExceptionUserTwoStepVerification";
	const FORM_BACKGROUND_ERROR                                         = "DivReturnMessageError";
	const FORM_BACKGROUND_SUCCESS                                       = "DivReturnMessageSuccess";
	const FORM_BACKGROUND_WARNING                                       = "DivReturnMessageWarning";
	const FORM_CAPTCHA_CONTACT                                          = "CaptchaContact";
	const FORM_CAPTCHA_REGISTER                                         = "CaptchaRegister";
	const FORM_FIELD_ERROR                                              = "InputAlertText";
	const FORM_FIELD_ASSOC_USER_CORPORATION_REGISTRATION_DATE_DAY       = "FormFieldAssocUserCorporationRegistrationDateDay";
	const FORM_FIELD_ASSOC_USER_CORPORATION_REGISTRATION_DATE_MONTH     = "FormFieldAssocUserCorporationRegistrationDateMonth";
	const FORM_FIELD_ASSOC_USER_CORPORATION_REGISTRATION_DATE_YEAR      = "FormFieldAssocUserCorporationRegistrationDateYear";
	const FORM_FIELD_ASSOC_USER_CORPORATION_REGISTRATION_ID             = "FormFieldAssocUserCorporationRegistrationId";
	const FORM_FIELD_CAPTCHA                                            = "FormFieldCaptcha";
	const FORM_FIELD_CORPORATION_ACTIVE                                 = "FormFieldCorporationActive";
	const FORM_FIELD_CORPORATION_NAME                                   = "FormFieldCorporationName";
	const FORM_FIELD_DEPARTMENT_INITIALS                                = "FormFieldDepartmentInitials";
	const FORM_FIELD_DEPARTMENT_NAME                                    = "FormFieldDepartmentName";
	const FORM_FIELD_DEPARTMENT_SELECT                                  = "FormFieldDepartmentSelect";
	const FORM_FIELD_HEADER_DEBUG                                       = "FormFieldHeaderDebug";
	const FORM_FIELD_HEADER_DEBUG_HIDDEN                                = "FormFieldHeaderDebugHidden";
	const FORM_FIELD_HEADER_LAYOUT                                      = "FormFieldHeaderLayout";
	const FORM_FIELD_HEADER_LAYOUT_HIDDEN                               = "FormFieldHeaderLayoutHidden";
	const FORM_FIELD_HEADER_LOG_OUT                                     = "FormFieldHeaderLogOut";
	const FORM_FIELD_LOGIN                                              = "FormFieldLogin";
	const FORM_FIELD_NOT_OBLIGATORY                                     = "FormFieldNotObligatory";
	const FORM_FIELD_NOTIFICATION_ACTIVE                                = "FormFieldNotificationActive";
	const FORM_FIELD_NOTIFICATION_ID                                    = "FormFieldNotificationId";
	const FORM_FIELD_NOTIFICATION_TEXT                                  = "FormFieldNotificationText";
	const FORM_FIELD_PASSWORD_NEW                                       = "FormFieldPasswordNew";
	const FORM_FIELD_PASSWORD_REPEAT                                    = "FormFieldPasswordRepeat";
	const FORM_FIELD_PASSWORD_RESET_CODE                                = "FormFieldPasswordResetCode";
	const FORM_FIELD_RADIO_DEPARTMENT                                   = "FormFieldRadioDepartment";
	const FORM_FIELD_RADIO_DEPARTMENT_NAME                              = "FormFieldRadioDepartmentName";
	const FORM_FIELD_RADIO_DEPARTMENT_NAME_AND_CORPORATION_NAME         = "FormFieldRadioDepartmentNameAndCorporationName";
	const FORM_FIELD_RADIO_SYSTEM_CONFIGURATION                         = "FormFieldRadioSystemConfiguration";
	const FORM_FIELD_RADIO_SYSTEM_CONFIGURATION_OPTION_NAME             = "FormFieldRadioSystemConfigurationOptionName";
	const FORM_FIELD_RADIO_SYSTEM_CONFIGURATION_OPTION_NUMBER           = "FormFieldRadioSystemConfigurationOptionNumber";
	const FORM_FIELD_RETURN_ERROR                                       = "FormFieldReturnError";
	const FORM_FIELD_SELECT_NONE                                        = "None";
	const FORM_FIELD_SYSTEM_CONFIGURATION_OPTION_ACTIVE                 = "FormFieldSystemConfigurationOptionActive";
	const FORM_FIELD_SYSTEM_CONFIGURATION_OPTION_DESCRIPTION            = "FormFieldSystemConfigurationOptionDescription";
	const FORM_FIELD_SYSTEM_CONFIGURATION_OPTION_NAME                   = "FormFieldSystemConfigurationOptionName";
	const FORM_FIELD_SYSTEM_CONFIGURATION_OPTION_NUMBER                 = "FormFieldSystemConfigurationOptionNumber";
	const FORM_FIELD_SYSTEM_CONFIGURATION_OPTION_VALUE                  = "FormFieldSystemConfigurationOptionValue";
	const FORM_FIELD_TEAM_DESCRIPTION                                   = "FormFieldTeamDescription";
	const FORM_FIELD_TEAM_ID                                            = "FormFieldTeamId";
	const FORM_FIELD_TEAM_NAME                                          = "FormFieldTeamName";
	const FORM_FIELD_TEAM_RADIO                                         = "FormFieldTeamRadio";
	const FORM_FIELD_TEAM_RADIO_DIV_ID                                  = "FormFieldTeamRadioDivId";
	const FORM_FIELD_TEAM_RADIO_DIV_NAME                                = "FormFieldTeamRadioDivName";
	const FORM_FIELD_TEAM_RADIO_ID                                      = "FormFieldTeamRadioId";
	const FORM_FIELD_TEAM_RADIO_NAME                                    = "FormFieldTeamRadioName";
	const FORM_FIELD_TICKET_DESCRIPTION                                 = "FormFieldTicketDescription";
	const FORM_FIELD_TICKET_ID                                          = "FormFieldTicketId";
	const FORM_FIELD_TICKET_RADIO                                       = "FormFieldTicketRadio";
	const FORM_FIELD_TICKET_RADIO_DIV_ID                                = "FormFieldTicketRadioDivId";
	const FORM_FIELD_TICKET_RADIO_DIV_TITLE                             = "FormFieldTicketRadioDivTitle";
	const FORM_FIELD_TICKET_RADIO_ID                                    = "FormFieldTicketRadioId";
	const FORM_FIELD_TICKET_RADIO_TITLE                                 = "FormFieldTicketRadioTitle";
	const FORM_FIELD_TICKET_TITLE                                       = "FormFieldTicketTitle";
	const FORM_FIELD_TICKET_TYPE                                        = "FormFieldTicketType";
	const FORM_FIELD_TYPE_ASSOC_USER_SERVICE_DESCRIPTION                = "FormFieldTypeAssocUserServiceDescription";
	const FORM_FIELD_TYPE_ASSOC_USER_TEAM_DESCRIPTION                   = "FormFieldTypeAssocUserTeamDescription";
	const FORM_FIELD_TYPE_STATUS_TICKET_DESCRIPTION                     = "FormFieldTypeStatusTicketDescription";
	const FORM_FIELD_TYPE_TICKET_DESCRIPTION                            = "FormFieldTypeTicketDescription";
	const FORM_FIELD_TYPE_USER_DESCRIPTION                              = "FormFieldTypeUserDescription";
	const FORM_FIELD_USER_ACTIVE                                        = "FormFieldUserActive";
	const FORM_FIELD_USER_BIRTH_DATE_DAY                                = "FormFieldUserBirthDateDay";
	const FORM_FIELD_USER_BIRTH_DATE_MONTH                              = "FormFieldUserBirthDateMonth";
	const FORM_FIELD_USER_BIRTH_DATE_YEAR                               = "FormFieldUserBirthDateYear";
	const FORM_FIELD_USER_CORPORATION_SELECT                            = "FormFieldUserCorporationSelect";
	const FORM_FIELD_USER_COUNTRY                                       = "FormFieldUserCountry";
	const FORM_FIELD_USER_CONFIRMED                                     = "FormFieldUserConfirmed";
	const FORM_FIELD_USER_EMAIL                                         = "FormFieldUserEmail";
	const FORM_FIELD_USER_GENDER                                        = "FormFieldGender";
	const FORM_FIELD_USER_HASH_CODE                                     = "FormFieldUserHashCode";
	const FORM_FIELD_USER_NAME                                          = "FormFieldUserName";
	const FORM_FIELD_USER_PHONE_PRIMARY                                 = "FormFieldUserPhonePrimary";
	const FORM_FIELD_USER_PHONE_PRIMARY_PREFIX                          = "FormFieldUserPhonePrimaryPrefix";
	const FORM_FIELD_USER_PHONE_SECONDARY                               = "FormFieldUserPhoneSecondary";
	const FORM_FIELD_USER_PHONE_SECONDARY_PREFIX                        = "FormFieldUserPhoneSecondaryPrefix";
	const FORM_FIELD_USER_REGION                                        = "FormFieldUserRegion";
	const FORM_FIELD_USER_SESSION_EXPIRES                               = "FormFieldUserSessionExpires";
	const FORM_FIELD_USER_TWO_STEP_VERIFICATION                         = "FormFieldUserTwoStepVerification";
	const FORM_FIELD_USER_UNIQUE_ID                                     = "FormFieldUserUniqueId";
	const FORM_LIST_INPUT_LIMIT_ONE                                     = "FormListInputLimitOne";
	const FORM_LIST_INPUT_LIMIT_TWO                                     = "FormListInputLimitTwo";
	const FORM_IMAGE_ERROR                                              = "Icons/IconFormError.png";
	const FORM_IMAGE_SUCCESS                                            = "Icons/IconFormSuccess.png";
	const FORM_IMAGE_WARNING                                            = "Icons/IconFormWarning.png";
	const FORM_LOGIN_TWO_STEP_VERIFICATION_CODE_SUBMIT                  = "FormLoginTwoStepVerificationCodeSubmit";
	const FORM_CORPORATION                                              = "FormCorporation";
	const FORM_CORPORATION_LIST                                         = "FormCorporationList";
	const FORM_CORPORATION_LIST_BACK                                    = "FormCorporationListBack";
	const FORM_CORPORATION_LIST_FORM                                    = "FormCorporationListForm";
	const FORM_CORPORATION_LIST_FORWARD                                 = "FormCorporationListForward";
	const FORM_CORPORATION_LIST_VIEW_USERS                              = "FormCorporationListViewUsers";
	const FORM_CORPORATION_LIST_VIEW_USERS_BACK                         = "FormCorporationListViewUsersBack";
	const FORM_CORPORATION_LIST_VIEW_USERS_FORWARD                      = "FormCorporationListViewUsersForward";
	const FORM_CORPORATION_REGISTER                                     = "FormCorporationRegister";
	const FORM_CORPORATION_REGISTER_CANCEL                              = "FormCorporationRegisterCancel";
	const FORM_CORPORATION_REGISTER_FORM                                = "FormCorporationRegisterForm";
	const FORM_CORPORATION_REGISTER_SUBMIT                              = "FormCorporationRegisterSubmit";
	const FORM_CORPORATION_SELECT                                       = "FormCorporationSelect";
	const FORM_CORPORATION_SELECT_FORM                                  = "FormCorporationSelectForm";
	const FORM_CORPORATION_SELECT_SUBMIT                                = "FormComporationSelectSubmit";
	const FORM_CORPORATION_UPDATE_CANCEL                                = "FormCorporationUpdateCancel";
	const FORM_CORPORATION_UPDATE_FORM                                  = "FormCorporationUpdateForm";
	const FORM_CORPORATION_UPDATE_SUBMIT                                = "FormCorporationUpdateSubmit";
	const FORM_CORPORATION_VIEW                                         = "FormCorporationView";
	const FORM_CORPORATION_VIEW_DELETE                                  = "FormCorporationViewDelete";
	const FORM_CORPORATION_VIEW_DELETE_SUBMIT                           = "FormCorporationViewDeleteSubmit";
	const FORM_CORPORATION_VIEW_LIST_USERS                              = "FormCorporationViewListUsers";
	const FORM_CORPORATION_VIEW_LIST_USERS_FORM                         = "FormCorporationViewListUsersForm";
	const FORM_CORPORATION_VIEW_LIST_USERS_SUBMIT                       = "FormCorporationViewListUsersSubmit";
	const FORM_CORPORATION_VIEW_LIST_USERS_SUBMIT_BACK                  = "FormCorporationViewListUsersSubmitBack";
	const FORM_CORPORATION_VIEW_LIST_USERS_SUBMIT_FORWARD               = "FormCorporationViewListUsersSubmitForward";
	const FORM_CORPORATION_VIEW_UPDATE                                  = "FormCorporationViewUpdate";
	const FORM_CORPORATION_VIEW_UPDATE_SUBMIT                           = "FormCorporationViewUpdateSubmit";
	const FORM_COUNTRY                                                  = "FormCountry";
	const FORM_COUNTRY_LIST                                             = "FormCountryList";
	const FORM_COUNTRY_LIST_BACK                                        = "FormCountryListBack";
	const FORM_COUNTRY_LIST_FORM                                        = "FormCountryListForm";
	const FORM_COUNTRY_LIST_FORWARD                                     = "FormCountryListForward";
	const FORM_DEPARTMENT                                               = "FormDepartment";
	const FORM_DEPARTMENT_LIST                                          = "FormDepartmentList";
	const FORM_DEPARTMENT_LIST_BACK                                     = "FormDepartmentListBack";
	const FORM_DEPARTMENT_LIST_FORM                                     = "FormDepartmentListForm";
	const FORM_DEPARTMENT_LIST_FORWARD                                  = "FormDepartmentListForward";
	const FORM_DEPARTMENT_REGISTER                                      = "FormDepartmentRegister";
	const FORM_DEPARTMENT_REGISTER_CANCEL                               = "FormDepartmentRegisterCancel";
	const FORM_DEPARTMENT_REGISTER_FORM                                 = "FormDepartmentRegisterForm";
	const FORM_DEPARTMENT_REGISTER_SUBMIT                               = "FormDepartmentRegisterSubmit";
	const FORM_DEPARTMENT_SELECT                                        = "FormDepartmentSelect";
	const FORM_DEPARTMENT_SELECT_FORM                                   = "FormDepartmentSelectForm";
	const FORM_DEPARTMENT_SELECT_SUBMIT                                 = "FormDepartmentSelectSubmit";
	const FORM_DEPARTMENT_UPDATE_CANCEL                                 = "FormDepartmentUpdateCancel";
	const FORM_DEPARTMENT_UPDATE_FORM                                   = "FormDepartmentUpdateForm";
	const FORM_DEPARTMENT_UPDATE_SUBMIT                                 = "FormDepartmentUpdateSubmit";
	const FORM_DEPARTMENT_VIEW                                          = "FormDepartmentView";
	const FORM_DEPARTMENT_VIEW_DELETE                                   = "FormDepartmentViewDelete";
	const FORM_DEPARTMENT_VIEW_DELETE_SUBMIT                            = "FormDepartmentViewDeleteSubmit";
	const FORM_DEPARTMENT_VIEW_LIST_USERS                               = "FormDepartmentViewListUsers";
	const FORM_DEPARTMENT_VIEW_LIST_USERS_FORM                          = "FormDepartmentViewListUsersForm";
	const FORM_DEPARTMENT_VIEW_LIST_USERS_SUBMIT                        = "FormDepartmentViewListUsersSubmit";
	const FORM_DEPARTMENT_VIEW_LIST_USERS_SUBMIT_BACK                   = "FormDepartmentViewListUsersSubmitBack";
	const FORM_DEPARTMENT_VIEW_LIST_USERS_SUBMIT_FORWARD                = "FormDepartmentViewListUsersSubmitForward";
	const FORM_DEPARTMENT_VIEW_UPDATE                                   = "FormDepartmentViewUpdate";
	const FORM_DEPARTMENT_VIEW_UPDATE_SUBMIT                            = "FormDepartmentViewUpdateSubmit";
	const FORM_LOGIN                                                    = "FormLogin";
	const FORM_NOTIFICATION                                             = "FormNotification";
	const FORM_NOTIFICATION_LIST                                        = "FormNotificationList";
	const FORM_NOTIFICATION_LIST_BACK                                   = "FormNotificationListBack";
	const FORM_NOTIFICATION_LIST_FORM                                   = "FormNotificationListForm";
	const FORM_NOTIFICATION_LIST_FORWARD                                = "FormNotificationListForward";
	const FORM_NOTIFICATION_REGISTER                                    = "FormNotificationRegister";
	const FORM_NOTIFICATION_REGISTER_CANCEL                             = "FormNotificationRegisterCancel";
	const FORM_NOTIFICATION_REGISTER_FORM                               = "FormNotificationRegisterForm";
	const FORM_NOTIFICATION_REGISTER_SUBMIT                             = "FormNotificationRegisterSubmit";
	const FORM_NOTIFICATION_RETURN_NOT_FOUND                            = "FormNotificationNotFound";
	const FORM_NOTIFICATION_SELECT                                      = "FormNotificationSelect";
	const FORM_NOTIFICATION_SELECT_FORM                                 = "FormNotificationSelectForm";
	const FORM_NOTIFICATION_SELECT_SUBMIT                               = "FormNotificationSelectSubmit";
	const FORM_NOTIFICATION_UPDATE_FORM                                 = "FormNotificationUpdateForm";
	const FORM_NOTIFICATION_UPDATE_CANCEL                               = "FormNotificationUpdateCancel";
	const FORM_NOTIFICATION_UPDATE_SUBMIT                               = "FormNotificationUpdateSubmit";
	const FORM_NOTIFICATION_VIEW                                        = "FormNotificationView";
	const FORM_NOTIFICATION_VIEW_DELETE                                 = "FormNotificationViewDelete";
	const FORM_NOTIFICATION_VIEW_DELETE_SUBMIT                          = "FormNotificationViewDeleteSubmit";
	const FORM_NOTIFICATION_VIEW_LIST_USERS                             = "FormNotificationViewListUsers";
	const FORM_NOTIFICATION_VIEW_LIST_USERS_FORM                        = "FormNotificationViewListUsersForm";
	const FORM_NOTIFICATION_VIEW_LIST_USERS_SUBMIT                      = "FormNotificationViewListUsersSubmit";
	const FORM_NOTIFICATION_VIEW_LIST_USERS_SUBMIT_BACK                 = "FormNotificationViewListUsersSubmitBack";
	const FORM_NOTIFICATION_VIEW_LIST_USERS_SUBMIT_FORWARD              = "FormNotificationViewListUsersSubmitForward";
	const FORM_NOTIFICATION_VIEW_UPDATE                                 = "FormSystemConfigurationViewUpdate";
	const FORM_NOTIFICATION_VIEW_UPDATE_SUBMIT                          = "FormSystemConfigurationViewUpdateSubmit";
	const FORM_SYSTEM_CONFIGURATION                                     = "FormSystemConfiguration";
	const FORM_SYSTEM_CONFIGURATION_LIST                                = "FormSystemConfigurationList";
	const FORM_SYSTEM_CONFIGURATION_LIST_BACK                           = "FormSystemConfigurationListBack";
	const FORM_SYSTEM_CONFIGURATION_LIST_FORM                           = "FormSystemConfigurationListForm";
	const FORM_SYSTEM_CONFIGURATION_LIST_FORWARD                        = "FormSystemConfigurationListForward";
	const FORM_SYSTEM_CONFIGURATION_REGISTER                            = "FormSystemConfigurationRegister";
	const FORM_SYSTEM_CONFIGURATION_REGISTER_CANCEL                     = "FormSystemConfigurationRegisterCancel";
	const FORM_SYSTEM_CONFIGURATION_REGISTER_FORM                       = "FormSystemConfigurationRegisterForm";
	const FORM_SYSTEM_CONFIGURATION_REGISTER_SUBMIT                     = "FormSystemConfigurationRegisterSubmit";
	const FORM_SYSTEM_CONFIGURATION_RETURN_NOT_FOUND                    = "FormSystemConfigurationNotFound";
	const FORM_SYSTEM_CONFIGURATION_SELECT                              = "FormSystemConfigurationSelect";
	const FORM_SYSTEM_CONFIGURATION_SELECT_FORM                         = "FormSystemConfigurationSelectForm";
	const FORM_SYSTEM_CONFIGURATION_SELECT_SUBMIT                       = "FormSystemConfigurationSelectSubmit";
	const FORM_SYSTEM_CONFIGURATION_UPDATE_FORM                         = "FormSystemConfigurationUpdateForm";
	const FORM_SYSTEM_CONFIGURATION_UPDATE_CANCEL                       = "FormSystemConfigurationUpdateCancel";
	const FORM_SYSTEM_CONFIGURATION_UPDATE_SUBMIT                       = "FormSystemConfigurationUpdateSubmit";
	const FORM_SYSTEM_CONFIGURATION_VIEW                                = "FormSystemConfigurationView";
	const FORM_SYSTEM_CONFIGURATION_VIEW_DELETE                         = "FormSystemConfigurationViewDelete";
	const FORM_SYSTEM_CONFIGURATION_VIEW_DELETE_SUBMIT                  = "FormSystemConfigurationViewDeleteSubmit";
	const FORM_SYSTEM_CONFIGURATION_VIEW_UPDATE                         = "FormSystemConfigurationViewUpdate";
	const FORM_SYSTEM_CONFIGURATION_VIEW_UPDATE_SUBMIT                  = "FormSystemConfigurationViewUpdateSubmit";
	const FORM_TEAM                                                     = "FormTeam";
	const FORM_TEAM_LIST                                                = "FormTeamList";
	const FORM_TEAM_LIST_BACK                                           = "FormTeamListBack";
	const FORM_TEAM_LIST_FORM                                           = "FormTeamListForm";
	const FORM_TEAM_LIST_FORWARD                                        = "FormTeamListForward";
	const FORM_TEAM_REGISTER                                            = "FormTeamRegister";
	const FORM_TEAM_REGISTER_CANCEL                                     = "FormTeamRegisterCancel";
	const FORM_TEAM_REGISTER_FORM                                       = "FormTeamRegisterForm";
	const FORM_TEAM_REGISTER_SUBMIT                                     = "FormTeamRegisterSubmit";
	const FORM_TEAM_RETURN_NOT_FOUND                                    = "FormTeamReturnNotFound";
	const FORM_TEAM_SELECT                                              = "FormTeamSelect";
	const FORM_TEAM_SELECT_FORM                                         = "FormTeamSelectForm";
	const FORM_TEAM_SELECT_SUBMIT                                       = "FormTeamSelectSubmit";
	const FORM_TEAM_UPDATE_CANCEL                                       = "FormTeamUpdateCancel";
	const FORM_TEAM_UPDATE_FORM                                         = "FormTeamUpdateForm";
	const FORM_TEAM_UPDATE_SUBMIT                                       = "FormTeamUpdateSubmit";
	const FORM_TEAM_VIEW                                                = "FormTeamView";
	const FORM_TEAM_VIEW_DELETE                                         = "FormTeamViewDelete";
	const FORM_TEAM_VIEW_DELETE_SUBMIT                                  = "FormTeamViewDeleteSubmit";
	const FORM_TEAM_VIEW_LIST_USERS                                     = "FormTeamViewListUsers";
	const FORM_TEAM_VIEW_LIST_USERS_FORM                                = "FormTeamViewListUsersForm";
	const FORM_TEAM_VIEW_LIST_USERS_SUBMIT                              = "FormTeamViewListUsersSubmit";
	const FORM_TEAM_VIEW_LIST_USERS_SUBMIT_BACK                         = "FormTeamViewListUsersSubmitBack";
	const FORM_TEAM_VIEW_LIST_USERS_SUBMIT_FORWARD                      = "FormTeamViewListUsersSubmitForward";
	const FORM_TEAM_VIEW_UPDATE                                         = "FormTeamViewUpdate";
	const FORM_TEAM_VIEW_UPDATE_SUBMIT                                  = "FormTeamViewUpdateSubmit";
	const FORM_TICKET                                                   = "FormTicket";
	const FORM_TICKET_LIST                                              = "FormTicketList";
	const FORM_TICKET_LIST_BACK                                         = "FormTicketListBack";
	const FORM_TICKET_LIST_FORM                                         = "FormTicketListForm";
	const FORM_TICKET_LIST_FORWARD                                      = "FormTicketListForward";
	const FORM_TICKET_LIST_SELECT                                       = "FormTicketListSelect";
	const FORM_TICKET_REGISTER                                          = "FormTicketRegister";
	const FORM_TICKET_REGISTER_CANCEL                                   = "FormTicketRegisterCancel";
	const FORM_TICKET_REGISTER_FORM                                     = "FormTicketRegisterForm";
	const FORM_TICKET_REGISTER_SUBMIT                                   = "FormTicketRegisterSubmit";
	const FORM_TICKET_SELECT                                            = "FormTicketSelect";
	const FORM_TICKET_SELECT_FORM                                       = "FormTicketSelectForm";
	const FORM_TICKET_SELECT_SUBMIT                                     = "FormTicketSelectSubmit";
	const FORM_TICKET_UPDATE                                            = "FormTicketUpdate";
	const FORM_TICKET_UPDATE_CANCEL                                     = "FormTicketUpdateCancel";
	const FORM_TICKET_UPDATE_FORM                                       = "FormTicketUpdateForm";
	const FORM_TICKET_UPDATE_SUBMIT                                     = "FormTicketUpdateSubmit";
	const FORM_TICKET_VIEW                                              = "FormTicketUpdateView";
	const FORM_TICKET_VIEW_DELETE                                       = "FormTicketViewDelete";
	const FORM_TICKET_VIEW_DELETE_SUBMIT                                = "FormTicketViewDeleteSubmit";
	const FORM_TICKET_VIEW_LIST_USERS                                   = "FormTicketViewListUsers";
	const FORM_TICKET_VIEW_LIST_USERS_FORM                              = "FormTicketViewListUsersForm";
	const FORM_TICKET_VIEW_LIST_USERS_SUBMIT                            = "FormTicketViewListUsersSubmit";
	const FORM_TICKET_VIEW_LIST_USERS_SUBMIT_BACK                       = "FormTicketViewListUsersSubmitBack";
	const FORM_TICKET_VIEW_LIST_USERS_SUBMIT_FORWARD                    = "FormTicketViewListUsersSubmitForward";
	const FORM_TICKET_VIEW_UPDATE                                       = "FormTicketViewUpdate";
	const FORM_TICKET_VIEW_UPDATE_SUBMIT                                = "FormTicketViewUpdateSubmit";
	const FORM_TYPE_ASSOC_USER_TEAM                                     = "FormTypeAssocUserTeam";
	const FORM_TYPE_ASSOC_USER_TEAM_LIST                                = "FormTypeAssocUserTeamList";
	const FORM_TYPE_ASSOC_USER_TEAM_LIST_BACK                           = "FormTypeAssocUserTeamListBack";
	const FORM_TYPE_ASSOC_USER_TEAM_LIST_FORM                           = "FormTypeAssocUserTeamListForm";
	const FORM_TYPE_ASSOC_USER_TEAM_LIST_FORWARD                        = "FormTypeAssocUserTeamListForward";
	const FORM_TYPE_ASSOC_USER_TEAM_REGISTER                            = "FormTypeAssocUserTeamReturnRegister";
	const FORM_TYPE_ASSOC_USER_TEAM_REGISTER_CANCEL                     = "FormTypeAssocUserTeamReturnCancel";
	const FORM_TYPE_ASSOC_USER_TEAM_REGISTER_FORM                       = "FormTypeAssocUserTeamReturnRegisterForm";
	const FORM_TYPE_ASSOC_USER_TEAM_REGISTER_SUBMIT                     = "FormTypeAssocUserTeamReturnSubmit";
	const FORM_TYPE_ASSOC_USER_TEAM_RETURN_NOT_FOUND                    = "FormTypeAssocUserTeamReturnNotFound";
	const FORM_TYPE_ASSOC_USER_TEAM_SELECT                              = "FormTypeAssocUserTeamSelect";
	const FORM_TYPE_ASSOC_USER_TEAM_SELECT_FORM                         = "FormTypeAssocUserTeamSelectForm";
	const FORM_TYPE_ASSOC_USER_TEAM_SELECT_SUBMIT                       = "FormTypeAssocUserTeamSelectSubmit";
	const FORM_TYPE_ASSOC_USER_TEAM_UPDATE_CANCEL                       = "FormTypeAssocUserTeamUpdateCancel";
	const FORM_TYPE_ASSOC_USER_TEAM_UPDATE_FORM                         = "FormTypeAssocUserTeamUpdateForm";
	const FORM_TYPE_ASSOC_USER_TEAM_UPDATE_SUBMIT                       = "FormTypeAssocUserTeamUpdateSubmit";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW                                = "FormTypeAssocUserTeamView";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW_DELETE                         = "FormTypeAssocUserTeamViewDelete";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW_DELETE_SUBMIT                  = "FormTypeAssocUserTeamViewDeleteSubmit";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW_LIST_USERS                     = "FormTypeAssocUserTeamViewListUsers";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW_LIST_USERS_FORM                = "FormTypeAssocUserTeamViewListUsersForm";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW_LIST_USERS_SUBMIT              = "FormTypeAssocUserTeamViewListUsersSubmit";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW_LIST_USERS_SUBMIT_BACK         = "FormTypeAssocUserTeamViewListUsersSubmitBack";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW_LIST_USERS_SUBMIT_FORWARD      = "FormTypeAssocUserTeamViewListUsersSubmitForward";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW_UPDATE                         = "FormTypeAssocUserTeamViewUpdate";
	const FORM_TYPE_ASSOC_USER_TEAM_VIEW_UPDATE_SUBMIT                  = "FormTypeAssocUserTeamViewUpdateSubmit";
	const FORM_TYPE_STATUS_TICKET                                       = "FormTypeStatusTicket";
	const FORM_TYPE_STATUS_TICKET_LIST                                  = "FormTypeStatusTicketList";
	const FORM_TYPE_STATUS_TICKET_LIST_BACK                             = "FormTypeStatusTicketListBack";
	const FORM_TYPE_STATUS_TICKET_LIST_FORM                             = "FormTypeStatusTicketListForm";
	const FORM_TYPE_STATUS_TICKET_LIST_FORWARD                          = "FormTypeStatusTicketListForward";
	const FORM_TYPE_STATUS_TICKET_LIST_SELECT_SUBMIT                    = "FormTypeStatusTicketListSelectSubmit";
	const FORM_TYPE_STATUS_TICKET_REGISTER                              = "FormTypeStatusTicketReturnRegister";
	const FORM_TYPE_STATUS_TICKET_REGISTER_CANCEL                       = "FormTypeStatusTicketReturnCancel";
	const FORM_TYPE_STATUS_TICKET_REGISTER_FORM                         = "FormTypeStatusTicketReturnForm";
	const FORM_TYPE_STATUS_TICKET_REGISTER_SUBMIT                       = "FormTypeStatusTicketReturnSubmit";
	const FORM_TYPE_STATUS_TICKET_RETURN_NOT_FOUND                      = "FormTypeStatusTicketReturnNotFound";
	const FORM_TYPE_STATUS_TICKET_SELECT                                = "FormTypeStatusTicketSelect";
	const FORM_TYPE_STATUS_TICKET_SELECT_FORM                           = "FormTypeStatusTicketSelectForm";
	const FORM_TYPE_STATUS_TICKET_SELECT_SUBMIT                         = "FormTypeStatusTicketSelectSubmit";
	const FORM_TYPE_STATUS_TICKET_UPDATE_CANCEL                         = "FormTypeStatusTicketUpdateCancel";
	const FORM_TYPE_STATUS_TICKET_UPDATE_FORM                           = "FormTypeStatusTicketUpdateForm";	
	const FORM_TYPE_STATUS_TICKET_UPDATE_SUBMIT                         = "FormTypeStatusTicketUpdateSubmit";
	const FORM_TYPE_STATUS_TICKET_VIEW                                  = "FormTypeStatusTicketView";
	const FORM_TYPE_STATUS_TICKET_VIEW_DELETE                           = "FormTypeStatusTicketViewDelete";
	const FORM_TYPE_STATUS_TICKET_VIEW_DELETE_SUBMIT                    = "FormTypeStatusTicketViewDeleteSubmit";
	const FORM_TYPE_STATUS_TICKET_VIEW_LIST_USERS                       = "FormTypeStatusTicketViewListUsers";
	const FORM_TYPE_STATUS_TICKET_VIEW_LIST_USERS_FORM                  = "FormTypeStatusTicketViewListUsersForm";
	const FORM_TYPE_STATUS_TICKET_VIEW_LIST_USERS_SUBMIT                = "FormTypeStatusTicketViewListUsersSubmit";
	const FORM_TYPE_STATUS_TICKET_VIEW_LIST_USERS_SUBMIT_BACK           = "FormTypeStatusTicketViewListUsersSubmitBack";
	const FORM_TYPE_STATUS_TICKET_VIEW_LIST_USERS_SUBMIT_FORWARD        = "FormTypeStatusTicketViewListUsersSubmitForward";
	const FORM_TYPE_STATUS_TICKET_VIEW_UPDATE                           = "FormTypeStatusTicketViewUpdate";
	const FORM_TYPE_STATUS_TICKET_VIEW_UPDATE_SUBMIT                    = "FormTypeStatusTicketViewUpdateSubmit";
	const FORM_TYPE_TICKET                                              = "FormTypeTicket";
	const FORM_TYPE_TICKET_LIST                                         = "FormTypeTicketList";
	const FORM_TYPE_TICKET_LIST_BACK                                    = "FormTypeTicketListBack";
	const FORM_TYPE_TICKET_LIST_FORM                                    = "FormTypeTicketListForm";
	const FORM_TYPE_TICKET_LIST_FORWARD                                 = "FormTypeTicketListForward";
	const FORM_TYPE_TICKET_REGISTER                                     = "FormTypeTicketReturnRegister";
	const FORM_TYPE_TICKET_REGISTER_CANCEL                              = "FormTypeTicketReturnCancel";
	const FORM_TYPE_TICKET_REGISTER_FORM                                = "FormTypeTicketReturnForm";
	const FORM_TYPE_TICKET_REGISTER_SUBMIT                              = "FormTypeTicketReturnSubmit";
	const FORM_TYPE_TICKET_RETURN_NOT_FOUND                             = "FormTypeTicketReturnNotFound";
	const FORM_TYPE_TICKET_SELECT                                       = "FormTypeTicketSelect";
	const FORM_TYPE_TICKET_SELECT_FORM                                  = "FormTypeTicketSelectForm";
	const FORM_TYPE_TICKET_SELECT_SUBMIT                                = "FormTypeTicketSelectSubmit";	
	const FORM_TYPE_TICKET_UPDATE_CANCEL                                = "FormTypeTicketUpdateCancel";
	const FORM_TYPE_TICKET_UPDATE_FORM                                  = "FormTypeTicketUpdateForm";
	const FORM_TYPE_TICKET_UPDATE_SUBMIT                                = "FormTypeTicketUpdateSubmit";
	const FORM_TYPE_TICKET_VIEW                                         = "FormTypeTicketView";
	const FORM_TYPE_TICKET_VIEW_DELETE                                  = "FormTypeTicketViewDelete";
	const FORM_TYPE_TICKET_VIEW_DELETE_SUBMIT                           = "FormTypeTicketViewDeleteSubmit";
	const FORM_TYPE_TICKET_VIEW_LIST_USERS                              = "FormTypeTicketViewListUsers";
	const FORM_TYPE_TICKET_VIEW_LIST_USERS_FORM                         = "FormTypeTicketViewListUsersForm";
	const FORM_TYPE_TICKET_VIEW_LIST_USERS_SUBMIT                       = "FormTypeTicketViewListUsersSubmit";
	const FORM_TYPE_TICKET_VIEW_LIST_USERS_SUBMIT_BACK                  = "FormTypeTicketViewListUsersSubmitBack";
	const FORM_TYPE_TICKET_VIEW_LIST_USERS_SUBMIT_FORWARD               = "FormTypeTicketViewListUsersSubmitForward";
	const FORM_TYPE_TICKET_VIEW_UPDATE                                  = "FormTypeTicketViewUpdate";
	const FORM_TYPE_TICKET_VIEW_UPDATE_SUBMIT                           = "FormTypeTicketViewUpdateSubmit";
	const FORM_TYPE_USER                                                = "FormTypeUser";
	const FORM_TYPE_USER_LIST                                           = "FormTypeUserList";
	const FORM_TYPE_USER_LIST_BACK                                      = "FormTypeUserListBack";
	const FORM_TYPE_USER_LIST_FORM                                      = "FormTypeUserListForm";
	const FORM_TYPE_USER_LIST_FORWARD                                   = "FormTypeUserListForward";
	const FORM_TYPE_USER_REGISTER                                       = "FormTypeUserReturnRegister";
	const FORM_TYPE_USER_REGISTER_CANCEL                                = "FormTypeUserReturnCancel";
	const FORM_TYPE_USER_REGISTER_FORM                                  = "FormTypeUserReturnRegister";
	const FORM_TYPE_USER_REGISTER_SUBMIT                                = "FormTypeUserReturnSubmit";
	const FORM_TYPE_USER_RETURN_NOT_FOUND                               = "FormTypeUserReturnNotFound";
	const FORM_TYPE_USER_SELECT                                         = "FormTypeUserSelect";
	const FORM_TYPE_USER_SELECT_FORM                                    = "FormTypeUserSelectForm";
	const FORM_TYPE_USER_SELECT_SUBMIT                                  = "FormTypeUserSelectSubmit";
	const FORM_TYPE_USER_UPDATE                                         = "FormTypeUserUpdate";	
	const FORM_TYPE_USER_UPDATE_CANCEL                                  = "FormTypeUserUpdateCancel";
	const FORM_TYPE_USER_UPDATE_FORM                                    = "FormTypeUserUpdateForm";	
	const FORM_TYPE_USER_UPDATE_SUBMIT                                  = "FormTypeUserUpdateSubmit";
	const FORM_TYPE_USER_VIEW                                           = "FormTypeUserView";
	const FORM_TYPE_USER_VIEW_DELETE_SUBMIT                             = "FormTypeUserViewDeleteSubmit";
	const FORM_TYPE_USER_VIEW_LIST_USERS                                = "FormTypeUsserViewListUsers";
	const FORM_TYPE_USER_VIEW_LIST_USERS_BACK                           = "FormTypeUsserViewListUsersBack";
	const FORM_TYPE_USER_VIEW_LIST_USERS_FORM                           = "FormTypeUsserViewListUsersForm";
	const FORM_TYPE_USER_VIEW_LIST_USERS_FORWARD                        = "FormTypeUsserViewListUsersForward";
	const FORM_TYPE_USER_VIEW_UPDATE_SUBMIT                             = "FormTypeUserViewUpdateSubmit";
	const FORM_USER_LIST                                                = "FormUserList";
	const FORM_USER_LIST_BACK                                           = "FormUserListBack";
	const FORM_USER_LIST_FORM                                           = "FormUserListForm";
	const FORM_USER_LIST_FORWARD                                        = "FormUserListForward";
	const FORM_USER_REGISTER                                            = "FormUserRegister";
	const FORM_USER_REGISTER_FORM                                       = "FormUserRegisterForm";
	const FORM_USER_REGISTER_SUBMIT                                     = "FormUserRegisterSubmit";
	const FORM_USER_RETURN_NOT_FOUND                                    = "FormUserReturnNotFound";
	const FORM_USER_SELECT                                              = "FormUserSelect";
	const FORM_USER_SELECT_FORM                                         = "FormUserSelectForm";
	const FORM_USER_SELECT_SUBMIT                                       = "FormUserSelectSubmit";
	const FORM_USER_UPDATE_CANCEL                                       = "FormUserUpdateCancel";
	const FORM_USER_UPDATE_FORM                                         = "FormUserUpdateForm";	
	const FORM_USER_UPDATE_SUBMIT                                       = "FormUserUpdateSubmit";
	const FORM_USER_VIEW                                                = "FormUserView";
	const FORM_USER_VIEW_ACTIVATE                                       = "FormUserViewActivate";
	const FORM_USER_VIEW_ACTIVATE_SUBMIT                                = "FormUserViewActivateSubmit";
	const FORM_USER_VIEW_CHANGE_ASSOC_USER_CORPORATION                  = "FormUserViewChangeAssocUserCorporation";
	const FORM_USER_VIEW_CHANGE_ASSOC_USER_CORPORATION_SUBMIT           = "FormUserViewChangeAssocUserCorporationSubmit";
	const FORM_USER_VIEW_CHANGE_CORPORATION                             = "FormUserViewChangeCorporation";
	const FORM_USER_VIEW_CHANGE_CORPORATION_SUBMIT                      = "FormUserViewChangeCorporationSubmit";
	const FORM_USER_VIEW_CHANGE_PASSWORD                                = "FormUserViewChangePassword";
	const FORM_USER_VIEW_CHANGE_PASSWORD_SUBMIT                         = "FormUserViewChangePasswordSubmit";
	const FORM_USER_VIEW_CHANGE_USER_TYPE                               = "FormUserViewChangeUserType";
	const FORM_USER_VIEW_CHANGE_USER_TYPE_SUBMIT                        = "FormUserViewChangeUserTypeSubmit";
	const FORM_USER_VIEW_DEACTIVATE                                     = "FormUserViewDeactivate";
	const FORM_USER_VIEW_DEACTIVATE_SUBMIT                              = "FormUserViewDeactivateSubmit";
	const FORM_USER_VIEW_DELETE                                         = "FormUserViewDelete";
	const FORM_USER_VIEW_DELETE_SUBMIT                                  = "FormUserViewDeleteSubmit";
	const FORM_USER_VIEW_RESET_PASSWORD                                 = "FormUserViewResetPassword";
	const FORM_USER_VIEW_RESET_PASSWORD_SUBMIT                          = "FormUserViewResetPasswordSubmit";
	const FORM_USER_VIEW_TWO_STEP_VERIFICATION_ACTIVATE                 = "FormUserViewTwoStepVerificationActivate";
	const FORM_USER_VIEW_TWO_STEP_VERIFICATION_ACTIVATE_SUBMIT          = "FormUserViewTwoStepVerificationActivateSubmit";
	const FORM_USER_VIEW_TWO_STEP_VERIFICATION_DEACTIVATE               = "FormUserViewTwoStepVerificationDeactivate";
	const FORM_USER_VIEW_TWO_STEP_VERIFICATION_DEACTIVATE_SUBMIT        = "FormUserViewTwoStepVerificationDeactivateSubmit";
	const FORM_USER_VIEW_UPDATE                                         = "FormUserViewUpdate";
	const FORM_USER_VIEW_UPDATE_SUBMIT                                  = "FormUserViewUpdateSubmit";
	const FORM_VALIDATE_FUNCTION_BOOL                                   = "FORM_VALIDATE_FUNCTION_BOOL";
	const FORM_VALIDATE_FUNCTION_CORPORATION_NAME                       = "FORM_VALIDATE_FUNCTION_CORPORATION_NAME";
	const FORM_VALIDATE_FUNCTION_COMPARE_STRING                         = "FORM_VALIDATE_FUNCTION_COMPARE_STRING";
	const FORM_VALIDATE_FUNCTION_COUNTRY_NAME                           = "FORM_VALIDATE_FUNCTION_COUNTRY_NAME";
	const FORM_VALIDATE_FUNCTION_COUNTRY_REGION_CODE                    = "FORM_VALIDATE_FUNCTION_COUNTRY_REGION_CODE";
	const FORM_VALIDATE_FUNCTION_CPF                                    = "FORM_VALIDATE_FUNCTION_CPF";
	const FORM_VALIDATE_FUNCTION_DATE                                   = "FORM_VALIDATE_FUNCTION_DATE";
	const FORM_VALIDATE_FUNCTION_DATE_DAY                               = "FORM_VALIDATE_FUNCTION_DATE_DAY";
	const FORM_VALIDATE_FUNCTION_DATE_MONTH                             = "FORM_VALIDATE_FUNCTION_DATE_MONTH";
	const FORM_VALIDATE_FUNCTION_DATE_YEAR                              = "FORM_VALIDATE_FUNCTION_DATE_YEAR";
	const FORM_VALIDATE_FUNCTION_DEPARTMENT_INITIALS                    = "FORM_VALIDATE_FUNCTION_DEPARTMENT_INITIALS";
	const FORM_VALIDATE_FUNCTION_DEPARTMENT_NAME                        = "FORM_VALIDATE_FUNCTION_DEPARTMENT_NAME";
	const FORM_VALIDATE_FUNCTION_DESCRIPTION                            = "FORM_VALIDATE_FUNCTION_DESCRIPTION";
	const FORM_VALIDATE_FUNCTION_EMAIL                                  = "FORM_VALIDATE_FUNCTION_EMAIL";
	const FORM_VALIDATE_FUNCTION_GENDER                                 = "FORM_VALIDATE_FUNCTION_GENDER";
	const FORM_VALIDATE_FUNCTION_HOST                                   = "FORM_VALIDATE_FUNCTION_HOST";
	const FORM_VALIDATE_FUNCTION_IP_ADDRESS                             = "FORM_VALIDATE_FUNCTION_IP_ADDRESS";
	const FORM_VALIDATE_FUNCTION_IP_MASK                                = "FORM_VALIDATE_FUNCTION_IP_MASK";
	const FORM_VALIDATE_FUNCTION_MESSAGE                                = "FORM_VALIDATE_FUNCTION_MESSAGE";
	const FORM_VALIDATE_FUNCTION_NAME                                   = "FORM_VALIDATE_FUNCTION_NAME";
	const FORM_VALIDATE_FUNCTION_NOT_NULL_OR_EMPTY                      = "FORM_VALIDATE_FUNCTION_NOT_NULL_OR_EMPTY";
	const FORM_VALIDATE_FUNCTION_NOT_NUMBER                             = "FORM_VALIDATE_FUNCTION_NOT_NUMBER";
	const FORM_VALIDATE_FUNCTION_NUMERIC                                = "FORM_VALIDATE_FUNCTION_NUMERIC";
	const FORM_VALIDATE_FUNCTION_PASSWORD                               = "FORM_VALIDATE_FUNCTION_PASSWORD";
	const FORM_VALIDATE_FUNCTION_REGISTRATION_ID                        = "FORM_VALIDATE_FUNCTION_REGISTRATION_ID";
	const FORM_VALIDATE_FUNCTION_SERVICE_NAME                           = "FORM_VALIDATE_FUNCTION_SERVICE_NAME";
	const FORM_VALIDATE_FUNCTION_SUBJECT                                = "FORM_VALIDATE_FUNCTION_SUBJECT";
	const FORM_VALIDATE_FUNCTION_TEAM_NAME                              = "FORM_VALIDATE_FUNCTION_TEAM_NAME";
	const FORM_VALIDATE_FUNCTION_TITLE                                  = "FORM_VALIDATE_FUNCTION_TITLE";
	const FORM_VALIDATE_FUNCTION_TYPE_ASSOC_USER_SERVICE                = "FORM_VALIDATE_FUNCTION_TYPE_ASSOC_USER_SERVICE";
	const FORM_VALIDATE_FUNCTION_TYPE_SERVICE                           = "FORM_VALIDATE_FUNCTION_TYPE_SERVICE";
	const FORM_VALIDATE_FUNCTION_URL                                    = "FORM_VALIDATE_FUNCTION_URL";
	const FORM_VALIDATE_FUNCTION_USER_UNIQUE_ID                         = "FORM_VALIDATE_FUNCTION_USER_UNIQUE_ID";
	const GET_ERROR_IP_ADDRESS_CLIENT                                   = "ReturnGetErrorIpAddressClient";
	const GET_ERROR_INVALID_OS                                          = "ReturnGetErrorInvalidOs";
	const HEAD_GENERIC                                                  = "HeadGeneric.php";
	const HEAD_JAVASCRIPT                                               = "HeadJavaScript.php";
	const HTACCESS_ERROR_FILE_CREATE                                    = "HtacessErrorFileCreate";
	const HTML_TAG_BODY_START                                           = "<body>";
	const HTML_TAG_BODY_END                                             = "</body>";
	const HTML_TAG_DOCTYPE                                              = "<!DOCTYPE html>";
	const HTML_TAG_END                                                  = "</html>";
	const HTML_TAG_HEAD_START                                           = "<head>";
	const HTML_TAG_HEAD_END              	                            = "</head>";
	const HTML_TAG_START                                                = "<html xmlns='http://www.w3.org/1999/xhtml' lang='pt'>";
	const INI_SET_FATAL_ERROR_DISPLAY_ERRORS                            = "IniSetFatalErrorDisplayErrors";
	const INI_SET_FATAL_ERROR_SESSION_SAVE_PATH                         = "IniSetFatalErrorSessionSavePath";
	const LANGUAGE_ENGLISH                                              = "Language/En";
	const LANGUAGE_GERMAN                                               = "Language/De";
	const LANGUAGE_PORTUGUESE                                           = "Language/Pt";
	const LANGUAGE_SPANISH                                              = "Language/Es";
	const LOCAL_IP                                                      = "127.0.0.1";
	const LOGIN_FORM_SUBMIT                                             = "LoginFormSubmit";
	const LOGIN_FORM_SUBMIT_FORGOT_PASSWORD                             = "LoginFormSubmitForgotPassword";
	const LOGIN_PASSWORD                                                = "LoginPassword";
	const LOGIN_TWO_STEP_VERIFICATION_ACTIVATED                         = "LoginTwoStepVerificationActivated";
	const LOGIN_TWO_STEP_VERIFICATION_CODE                              = "LoginTwoStepVerificationCode";
	const LOGIN_TWO_STEP_VERIFICATION_FORM                              = "LoginTwoStepVerificationForm";
	const MYSQL_ASSOC_USER_CORPORATION_DELETE_FAILED                    = "RetMySqlAssocUserCorporationDeleteFailed";
	const MYSQL_ASSOC_USER_CORPORATION_INSERT_FAILED                    = "RetMySqlAssocUserCorporationInsertFailed";
	const MYSQL_CHATSET_UTF8                                            = "utf8";
	const MYSQL_CORPORATION_DELETE_FAILED                               = "RetMySqlCorporationDeleteFailed";
	const MYSQL_CORPORATION_INSERT_FAILED                               = "RetMySqlCorporationInsertFailed";
	const MYSQL_CORPORATION_SELECT_BY_NAME_FAILED                       = "RetMySqlCorporationSelectByNameFailed";
	const MYSQL_CORPORATION_SELECT_BY_NAME_FETCH_FAILED                 = "RetMySqlCorporationSelectByNameFetchFailed";
	const MYSQL_CORPORATION_SELECT_FAILED                               = "RetMySqlCorporationInsertFailed";
	const MYSQL_CORPORATION_SELECT_FETCH_FAILED                         = "RetMySqlCorporationInsertFetchFailed";
	const MYSQL_CORPORATION_UPDATE_FAILED                               = "RetMySqlCorporationUpdateFailed";
	const MYSQL_COUNTRY_SELECT_FAILED                                   = "RetMySqlCountrySelectFailed";
	const MYSQL_COUNTRY_SELECT_FETCH_FAILED                             = "RetMySqlCountrySelectFetchFailed";
	const MYSQL_DEPARTMENT_DELETE_FAILED                                = "RetMySqlDepartmentDeleteFailed";
	const MYSQL_DEPARTMENT_INSERT_FAILED                                = "RetMySqlDepartmentInsertFailed";
	const MYSQL_DEPARTMENT_SELECT_BY_CORP_DEP_FAILED                    = "RetMySqlDepartmentSelectByCorpDepFailed";
	const MYSQL_DEPARTMENT_SELECT_BY_CORP_DEP_FETCH_FAILED              = "RetMySqlDepartmentSelectByCorpDepFetchFailed";
	const MYSQL_DEPARTMENT_SELECT_BY_CORPORATION_NAME_FAILED            = "RetMySqlDepartmentSelectByCorporationFailed";
	const MYSQL_DEPARTMENT_SELECT_BY_CORPORATION_NAME_FETCH_FAILED      = "RetMySqlDepartmentSelectByCorporationFetchFailed";
	const MYSQL_DEPARTMENT_SELECT_BY_DEPARTMENT_NAME_FAILED             = "RetMySqlDepartmentSelectByDepartmentNameFailed";
	const MYSQL_DEPARTMENT_SELECT_BY_DEPARTMENT_NAME_FETCH_FAILED       = "RetMySqlDepartmentSelectByDepartmentNameFetchFailed";
	const MYSQL_DEPARTMENT_SELECT_FAILED                                = "RetMySqlDepartmentSelectFailed";
	const MYSQL_DEPARTMENT_SELECT_FETCH_FAILED                          = "RetMySqlDepartmentSelectFetchFailed";
	const MYSQL_DEPARTMENT_UPDATE_CORPORATION_FAILED                    = "RetMySqlDepartmentUpdateCorporationFailed";
	const MYSQL_DEPARTMENT_UPDATE_FAILED                                = "RetMySqlDepartmentUpdateFailed";
	const MYSQL_ERROR_CODE_FOREIGN_KEY_DELETE_RESTRICT                  = "1451";
	const MYSQL_ERROR_CODE_FOREIGN_KEY_INSERT_RESTRICT                  = "1452";
	const MYSQL_ERROR_CODE_SYNTAX                                       = "1064";
	const MYSQL_ERROR_CODE_UNIQUE_KEY_DUPLICATE                         = "1062";
	const MYSQL_ERROR_CODE_ACCESS_DENIED                                = "1045";
	const MYSQL_ERROR_CONNECTION_CLOSE                                  = "RetMySqlErrorConnectionClose";
	const MYSQL_ERROR_CONNECTION_EMPTY                                  = "RetMySqlErrorConnectionEmpty";
	const MYSQL_ERROR_CONNECTION_NOT_EMPTY                              = "RetMySqlErrorConnectionNotEmpty";
	const MYSQL_ERROR_CONNECTION_OPEN                                   = "RetMySqlErrorConnectionOpen";
	const MYSQL_ERROR_CONNECTION_REFUSED                                = "RetMySqlErrorConnectionRefused";
	const MYSQL_ERROR_CONNECTION_FAILED                                 = "RetMySqlErrorConnectionFailed";
	const MYSQL_ERROR_DATABASE_NOT_FOUND                                = "RetMySqlErrorDataBaseNotFound";
	const MYSQL_ERROR_IMPORT_NO_INSERTS                                 = "RetMySqlErrorImportNoInserts";
	const MYSQL_ERROR_IMPORT_QUERY_SYNTAX                               = "RetMySqlErrorImportQuerySyntax";
	const MYSQL_ERROR_INSERT_FAILED                                     = "RetMySqlErrorInsertFailed";
	const MYSQL_ERROR_QUERY_PREPARE                                     = "RetMySqlErrorQueryPrepare";
 	const MYSQL_ERROR_QUERY_EMPTY                                       = "RetMySqlErrorQueryEmpty";
	const MYSQL_ERROR_QUERY_SQL                                         = "RetMySqlErrorQuerySql";
	const MYSQL_ERROR_UPDATE_SAME_VALUE                                 = "RetMySqlErrorUpdateSameValue";
	const MYSQL_ERROR_USER_EXISTS                                       = "RetMySqlErrorUserExists";
	const MYSQL_ERROR_USER_PERMISSION_DENIED                            = "RetMySqlErrorUserPermissionDenied";
	const MYSQL_INFRATOOLS_DATABASE_CHECK_TABLES_CORRUPT_FAILED         = "MySqlInfraToolsDataBaseCheckTablesCorruptFailed";
	const MYSQL_INFRATOOLS_DATABASE_CHECK_TABLES_FAILED                 = "MySqlInfraToolsDataBaseCheckTablesFailed";
	const MYSQL_INFRATOOLS_DATABASE_CHECK_TABLES_FETCH_FAILED           = "MySqlInfraToolsDataBaseCheckTablesFetchFailed";
	const MYSQL_INFRATOOLS_DATABASE_GET_ROW_COUNT_FAILED                = "MySqlInfraToolsDataBaseGetRowCountFailed";
	const MYSQL_INFRATOOLS_DATABASE_GET_ROW_COUNT_FETCH_FAILED          = "MySqlInfraToolsDataBaseGetRowCountFetchFailed";
	const MYSQL_LOG_ERROR                                               = "LogMySqlError";
	const MYSQL_LOG_QUERY                                               = "LogMySqlQuery";
	const MYSQL_NOTIFICATION_DELETE_FAILED                              = "RetMySqlNotificationDeleteFailed";
	const MYSQL_NOTIFICATION_DELETE_FAILED_NOT_FOUND                    = "RetMySqlNotificationDeleteFailedNotFound";
	const MYSQL_NOTIFICATION_INSERT_FAILED                              = "RetMySqlNotificationInsertFailed";
	const MYSQL_NOTIFICATION_SELECT_FAILED                              = "RetMySqlNotificationSelectFailed";
	const MYSQL_NOTIFICATION_SELECT_FETCH_FAILED                        = "RetMySqlNotificationSelectFetchFailed";
	const MYSQL_NOTIFICATION_UPDATE_FAILED                              = "RetMySqlNotificationUpdateFailed";
	const MYSQL_SYSTEM_CONFIGURATION_DELETE_FAILED                      = "RetMySqlSystemConfigurationDeleteFailed";
	const MYSQL_SYSTEM_CONFIGURATION_DELETE_FAILED_NOT_FOUND            = "RetMySqlSystemConfigurationDeleteFailedNotFound";
	const MYSQL_SYSTEM_CONFIGURATION_INSERT_FAILED                      = "RetMySqlSystemConfigurationInsertFailed";
	const MYSQL_SYSTEM_CONFIGURATION_SELECT_BY_OPTION_NAME_FAILED       = "RetMySqlSystemConfigurationSelectByOptionNameFailed"; 
	const MYSQL_SYSTEM_CONFIGURATION_SELECT_BY_OPTION_NAME_FETCH_FAILED = "RetMySqlSystemConfigurationSelectByOptionNameFetchFailed";
	const MYSQL_SYSTEM_CONFIGURATION_SELECT_BY_OPTION_NUMB_FAILED       = "RetMySqlSystemConfigurationSelectByOptionNumberFailed"; 
	const MYSQL_SYSTEM_CONFIGURATION_SELECT_BY_OPTION_NUMB_FETCH_FAILED = "RetMySqlSystemConfigurationSelectByOptionNumberFetchFailed";
	const MYSQL_SYSTEM_CONFIGURATION_SELECT_FAILED                      = "RetMySqlSystemConfigurationSelectFailed"; 
	const MYSQL_SYSTEM_CONFIGURATION_SELECT_FETCH_FAILED                = "RetMySqlSystemConfigurationSelectFetchFailed";
	const MYSQL_SYSTEM_CONFIGURATION_UPDATE_FAILED                      = "RetMySqlSystemConfigurationUpdateFailed";
	const MYSQL_TEAM_DELETE_BY_TEAM_DESCRIPTION_FAILED                  = "RetMySqlTeamDeleteByTeamDescriptionFailed";
	const MYSQL_TEAM_DELETE_BY_TEAM_DESCRIPTION_FAILED_NOT_FOUND        = "RetMySqlTeamDeleteByTeamDescriptionFailedNotFound";
	const MYSQL_TEAM_DELETE_BY_TEAM_ID_FAILED                           = "RetMySqlTeamDeleteByTeamIdFailed";
	const MYSQL_TEAM_DELETE_BY_TEAM_ID_FAILED_NOT_FOUND                 = "RetMySqlTeamDeleteByTeamIdFailedNotFound";
	const MYSQL_TEAM_SELECT_BY_TEAM_DESCRIPTION_FAILED                  = "RetMySqlTeamSelectByDescriptionFailed";
	const MYSQL_TEAM_SELECT_BY_TEAM_DESCRIPTION_FETCH_FAILED            = "RetMySqlTeamSelectByDescriptionFetchFailed";
	const MYSQL_TEAM_SELECT_BY_TEAM_ID_FAILED                           = "RetMySqlTeamSelectByTeamIdFailed";
	const MYSQL_TEAM_SELECT_BY_TEAM_ID_FETCH_FAILED                     = "RetMySqlTeamSelectByTeamIdFetchFailed";
	const MYSQL_TEAM_SELECT_BY_TEAM_NAME_FAILED                         = "RetMySqlTeamSelectByTeamNameFailed";
	const MYSQL_TEAM_SELECT_BY_TEAM_NAME_FETCH_FAILED                   = "RetMySqlTeamSelectByTeamNameFetchFailed";
	const MYSQL_TEAM_SELECT_FAILED                                      = "RetMySqlTeamSelectFailed";
	const MYSQL_TEAM_SELECT_FETCH_FAILED                                = "RetMySqlTeamSelectFetchFailed";
	const MYSQL_TEAM_UPDATE_FAILED                                      = "RetMySqlTeamUpdateFailed";
	const MYSQL_TYPE_ASSOC_USER_TEAM_DELETE_FAILED                      = "RetMySqlTypeAssocUserTeamDeleteFailed";
	const MYSQL_TYPE_ASSOC_USER_TEAM_DELETE_FAILED_NOT_FOUND            = "RetMySqlTypeAssocUserTeamDeleteFailedNotFound";
	const MYSQL_TYPE_ASSOC_USER_TEAM_SELECT_BY_DESCRIPTION_FAILED       = "RetMySqlTypeAssocUserTeamSelectByDescriptionFailed";
	const MYSQL_TYPE_ASSOC_USER_TEAM_SELECT_BY_DESCRIPTION_FETCH_FAILED = "RetMySqlTypeAssocUserTeamSelectByDescriptionFetchFailed";
	const MYSQL_TYPE_ASSOC_USER_TEAM_SELECT_BY_ID_FAILED                = "RetMySqlTypeAssocUserTeamSelectByIdFailed";
	const MYSQL_TYPE_ASSOC_USER_TEAM_SELECT_BY_ID_FETCH_FAILED          = "RetMySqlTypeAssocUserTeamSelectByIdFetchFailed";
	const MYSQL_TYPE_ASSOC_USER_TEAM_SELECT_FAILED                      = "RetMySqlTypeAssocUserTeamSelectFailed";
	const MYSQL_TYPE_ASSOC_USER_TEAM_SELECT_FETCH_FAILED                = "RetMySqlTypeAssocUserTeamSelectFetchFailed";
	const MYSQL_TYPE_ASSOC_USER_TEAM_UPDATE_FAILED                      = "RetMySqlTypeAssocUserTeamUpdateFailed";
	const MYSQL_TYPE_TICKET_DELETE_FAILED                               = "RetMySqlTypeTicketDeleteFailed";
	const MYSQL_TYPE_TICKET_DELETE_FAILED_NOT_FOUND                     = "RetMySqlTypeTicketDeleteFailedNotFound";
	const MYSQL_TYPE_TICKET_SELECT_BY_DESCRIPTION_FAILED                = "RetMySqlTypeTicketSelectByTypeTicketDescriptionFailed";
	const MYSQL_TYPE_TICKET_SELECT_BY_DESCRIPTION_FETCH_FAILED          = "RetMySqlTypeTicketSelectByTypeTicketDescriptionFetchFailed";
	const MYSQL_TYPE_TICKET_SELECT_FAILED                               = "RetMySqlTypeTicketSelectFailed";
	const MYSQL_TYPE_TICKET_SELECT_FETCH_FAILED                         = "RetMySqlTypeTicketSelectFetchFailed";
	const MYSQL_TYPE_TICKET_UPDATE_FAILED                               = "RetMySqlTypeTicketUpdateByTypeTicketDescriptionFailed";
	const MYSQL_TYPE_USER_DELETE_FAILED                                 = "RetMySqlTypeUserDeleteFailed";
	const MYSQL_TYPE_USER_DELETE_FAILED_NOT_FOUND                       = "RetMySqlTypeUserDeleteFailedNotFound";
	const MYSQL_TYPE_USER_SELECT_BY_DESCRIPTION_FAILED                  = "RetMySqlTypeUserSelectByDescriptionFailed";
	const MYSQL_TYPE_USER_SELECT_BY_DESCRIPTION_FETCH_FAILED            = "RetMySqlTypeUserSelectByDescriptionFetchFailed";
	const MYSQL_TYPE_USER_SELECT_BY_ID_FAILED                           = "RetMySqlTypeUserSelectByIdFailed";
	const MYSQL_TYPE_USER_SELECT_BY_ID_FETCH_FAILED                     = "RetMySqlTypeUserSelectByIdFetchFailed";
	const MYSQL_TYPE_USER_SELECT_FAILED                                 = "RetMySqlTypeUserSelectFailed";
	const MYSQL_TYPE_USER_SELECT_FETCH_FAILED                           = "RetMySqlTypeUserSelectFetchFailed";
	const MYSQL_TYPE_USER_UPDATE_FAILED                                 = "RetMySqlTypeUserUpdateFailed";
	const MYSQL_USER_CHECK_HASH_ACTIVE_ACCOUNT_FAILED                   = "RetMySqlUserCheckHasActiveAccountFailed";
	const MYSQL_USER_CHECK_PASSWORD_BY_EMAIL_FAILED                     = "RetMySqlUserCheckPasswordByEmailFailed";
	const MYSQL_USER_CHECK_PASSWORD_BY_USER_UNIQUE_ID_FAILED            = "RetMySqlUserCheckPasswordByUserUniqueIdFailed";
	const MYSQL_USER_INSERT_FAILED                                      = "RetMySqlUserInsertFailed";
	const MYSQL_USER_DELETE_FAILED                                      = "RetMySqlUserDeleteFailed";
	const MYSQL_USER_DELETE_FAILED_NOT_FOUND                            = "RetMySqlUserDeleteFailedNotFound";
	const MYSQL_USER_SELECT_FAILED                                      = "RetMySqlUserSelectFailed";
	const MYSQL_USER_SELECT_FETCH_FAILED                                = "RetMySqlUserSelectFetchFailed";
	const MYSQL_USER_SELECT_BY_HASH_CODE_FAILED                         = "RetMySqlUserSelectByHashCodeFailed";
	const MYSQL_USER_SELECT_BY_HASH_CODE_FETCH_FAILED                   = "RetMySqlUserSelectByHashCodeFetchFailed";
	const MYSQL_USER_SELECT_BY_USER_EMAIL_FAILED                        = "RetMySqlUserSelectByUserEmailFailed";
	const MYSQL_USER_SELECT_BY_USER_EMAIL_FETCH_FAILED                  = "RetMySqlUserSelectByUserEmailFetchFailed";
	const MYSQL_USER_SELECT_BY_USER_UNIQUE_ID_FAILED                    = "RetMySqlUserSelectByUserUniqueIdFailed";
	const MYSQL_USER_SELECT_BY_USER_UNIQUE_ID_FETCH_FAILED              = "RetMySqlUserSelectByUserUniqueIdFetchFailed";
	const MYSQL_USER_SELECT_EXISTS_BY_USER_EMAIL_FAILED                 = "RetMySqlUserSelectExistsByUserEmailFailed";
	const MYSQL_USER_SELECT_HASH_BY_EMAIL_FAILED                  		= "RetMySqlUserSelectHashByEmailFailed";
	const MYSQL_USER_SELECT_TEAM_BY_USER_EMAIL_EMPTY                    = "RetMySqlUserSelectTeamByUserEmailEmpty";
	const MYSQL_USER_SELECT_TEAM_BY_USER_EMAIL_FAILED                   = "RetMySqlUserSelectTeamByUserEmailFailed";
	const MYSQL_USER_SELECT_TEAM_BY_USER_EMAIL_FETCH_FAILED             = "RetMySqlUserSelectTeamByUserEmailFetchFailed";
	const MYSQL_USER_UPDATE_ASSOC_USER_CORPORATION_BY_EMAIL_FAILED      = "RetMySqlUpdateAssocUserCorporationByEmailFailed";
	const MYSQL_USER_UPDATE_BY_EMAIL_FAILED                             = "RetMySqlUserUpdateByEmailFailed";
	const MYSQL_USER_UPDATE_CORPORATION_BY_EMAIL_FAILED                 = "RetMySqlUserUpdateCorporationByEmail";
	const MYSQL_USER_UPDATE_DEPARTMENT_BY_CORPORATION_EMAIL_FAILED      = "RetMySqlUserUpdateDepartmentByCorporationEmailFailed";
	const MYSQL_USER_UPDATE_PASSWORD_BY_EMAIL_FAILED                    = "RetMySqlUserUpdatePasswordByEmailFailed";
	const MYSQL_USER_UPDATE_TWO_STEP_VERIFICATION_BY_EMAIL_FAILED       = "RetMySqlUserUpdateTwoStepVerificationByEmailFailed";
	const MYSQL_USER_UPDATE_USER_TYPE_BY_EMAIL_FAILED                   = "RetMySqlUserUpdateUserTypeByEmailFailed";
	const MYSQL_USER_UPDATE_UNIQUE_ID_BY_EMAIL_FAILED                   = "RetMySqlUserUpdateUniqueIdByEmailFailed";
	const PAGE                                                          = "Page";
	const PAGE_ABOUT                                                    = "Page_About";
	const PAGE_ACCOUNT                                                  = "Page_Account";
	const PAGE_ACCOUNT_CHANGE_PASSWORD                                  = "Page_Account_Change_Password";
	const PAGE_ACCOUNT_UPDATE                                           = "Page_Account_Update";
	const PAGE_ADMIN                                                    = "Page_Admin";
	const PAGE_ADMIN_CORPORATION                                        = "Page_Admin_Corporation";
	const PAGE_ADMIN_CORPORATION_LIST                                   = "Page_Admin_Corporation_List";
	const PAGE_ADMIN_CORPORATION_REGISTER                               = "Page_Admin_Corporation_Register";
	const PAGE_ADMIN_CORPORATION_SELECT                                 = "Page_Admin_Corporation_Select";
	const PAGE_ADMIN_CORPORATION_UPDATE                                 = "Page_Admin_Corporation_Update";
	const PAGE_ADMIN_CORPORATION_VIEW                                   = "Page_Admin_Corporation_View";
	const PAGE_ADMIN_CORPORATION_VIEW_USERS                             = "Page_Admin_Corporation_View_Users";
	const PAGE_ADMIN_COUNTRY                                            = "Page_Admin_Country";
	const PAGE_ADMIN_COUNTRY_LIST                                       = "Page_Admin_Country_List";
	const PAGE_ADMIN_DEPARTMENT                                         = "Page_Admin_Department";
	const PAGE_ADMIN_DEPARTMENT_LIST                                    = "Page_Admin_Department_List";
	const PAGE_ADMIN_DEPARTMENT_REGISTER                                = "Page_Admin_Department_Register";
	const PAGE_ADMIN_DEPARTMENT_SELECT                                  = "Page_Admin_Department_Select";
	const PAGE_ADMIN_DEPARTMENT_UPDATE                                  = "Page_Admin_Department_Update";
	const PAGE_ADMIN_DEPARTMENT_VIEW                                    = "Page_Admin_Department_View";
	const PAGE_ADMIN_DEPARTMENT_VIEW_USERS                              = "Page_Admin_Department_View_Users";
	const PAGE_ADMIN_NOTIFICATION                                       = "Page_Admin_Notification";
	const PAGE_ADMIN_NOTIFICATION_LIST                                  = "Page_Admin_Notification_List";
	const PAGE_ADMIN_NOTIFICATION_REGISTER                              = "Page_Admin_Notification_Register";
	const PAGE_ADMIN_NOTIFICATION_SELECT                                = "Page_Admin_Notification_Select";
	const PAGE_ADMIN_NOTIFICATION_UPDATE                                = "Page_Admin_Notification_Update";
	const PAGE_ADMIN_NOTIFICATION_VIEW                                  = "Page_Admin_Notification_View";
	const PAGE_ADMIN_NOTIFICATION_VIEW_USERS                            = "Page_Admin_Notification_View_Users";
	const PAGE_ADMIN_SYSTEM_CONFIGURATION                               = "Page_Admin_System_Configuration";
	const PAGE_ADMIN_SYSTEM_CONFIGURATION_LIST                          = "Page_Admin_System_Configuration_List";
	const PAGE_ADMIN_SYSTEM_CONFIGURATION_REGISTER                      = "Page_Admin_System_Configuration_Register";
	const PAGE_ADMIN_SYSTEM_CONFIGURATION_SELECT                        = "Page_Admin_System_Configuration_Select";
	const PAGE_ADMIN_SYSTEM_CONFIGURATION_UPDATE                        = "Page_Admin_System_Configuration_Update";
	const PAGE_ADMIN_SYSTEM_CONFIGURATION_VIEW                          = "Page_Admin_System_Configuration_View";
	const PAGE_ADMIN_STATUS_TICKET                                      = "Page_Admin_Status_Ticket";
	const PAGE_ADMIN_STATUS_TICKET_LIST                                 = "Page_Admin_Status_Ticket_List";
	const PAGE_ADMIN_STATUS_TICKET_REGISTER                             = "Page_Admin_Status_Ticket_Register";
	const PAGE_ADMIN_STATUS_TICKET_SELECT                               = "Page_Admin_Status_Ticket_Select";
	const PAGE_ADMIN_STATUS_TICKET_UPDATE                               = "Page_Admin_Status_Ticket_Update";
	const PAGE_ADMIN_STATUS_TICKET_VIEW                                 = "Page_Admin_Status_Ticket_View";
	const PAGE_ADMIN_TEAM                                               = "Page_Admin_Team";
	const PAGE_ADMIN_TEAM_ASSIGN_USER                                   = "Page_Admin_Team_Assign_User";
	const PAGE_ADMIN_TEAM_LIST                                          = "Page_Admin_Team_List";
	const PAGE_ADMIN_TEAM_REGISTER                                      = "Page_Admin_Team_Register";
	const PAGE_ADMIN_TEAM_SELECT                                        = "Page_Admin_Team_Select";
	const PAGE_ADMIN_TEAM_UPDATE                                        = "Page_Admin_Team_Update";
	const PAGE_ADMIN_TEAM_VIEW                                          = "Page_Admin_Team_View";
	const PAGE_ADMIN_TEAM_VIEW_LIST_USERS                               = "Page_Admin_Team_View_List_Users";
	const PAGE_ADMIN_TECH_INFO                                          = "Page_Admin_Tech_Info";
	const PAGE_ADMIN_TICKET                                             = "Page_Admin_Ticket";
	const PAGE_ADMIN_TICKET_ASSOCIATE                                   = "Page_Admin_Ticket_Associate";
	const PAGE_ADMIN_TICKET_LIST                                        = "Page_Admin_Ticket_List";
	const PAGE_ADMIN_TICKET_REGISTER                                    = "Page_Admin_Ticket_Register";
	const PAGE_ADMIN_TICKET_SELECT                                      = "Page_Admin_Ticket_Select";
	const PAGE_ADMIN_TICKET_UPDATE                                      = "Page_Admin_Ticket_Update";
	const PAGE_ADMIN_TICKET_VIEW                                        = "Page_Admin_Ticket_View";
	const PAGE_ADMIN_TYPE_ASSOC_USER_TEAM                               = "Page_Admin_Type_Assoc_User_Team";
	const PAGE_ADMIN_TYPE_ASSOC_USER_TEAM_LIST                          = "Page_Admin_Type_Assoc_User_Team_List";
	const PAGE_ADMIN_TYPE_ASSOC_USER_TEAM_REGISTER                      = "Page_Admin_Type_Assoc_User_Team_Register";
	const PAGE_ADMIN_TYPE_ASSOC_USER_TEAM_SELECT                        = "Page_Admin_Type_Assoc_User_Team_Select";
	const PAGE_ADMIN_TYPE_ASSOC_USER_TEAM_UPDATE                        = "Page_Admin_Type_Assoc_User_Team_Update";
	const PAGE_ADMIN_TYPE_ASSOC_USER_TEAM_VIEW                          = "Page_Admin_Type_Assoc_User_Team_View";
	const PAGE_ADMIN_TYPE_ASSOC_USER_TEAM_VIEW_LIST_USERS               = "Page_Admin_Type_Assoc_User_Team_View_List_Users";
	const PAGE_ADMIN_TYPE_STATUS_TICKET                                 = "Page_Admin_Type_Status_Ticket";
	const PAGE_ADMIN_TYPE_STATUS_TICKET_LIST                            = "Page_Admin_Type_Status_Ticket_List";
	const PAGE_ADMIN_TYPE_STATUS_TICKET_REGISTER                        = "Page_Admin_Type_Status_Ticket_Register";
	const PAGE_ADMIN_TYPE_STATUS_TICKET_SELECT                          = "Page_Admin_Type_Status_Ticket_Select";
	const PAGE_ADMIN_TYPE_STATUS_TICKET_UPDATE                          = "Page_Admin_Type_Status_Ticket_Update";
	const PAGE_ADMIN_TYPE_STATUS_TICKET_VIEW                            = "Page_Admin_Type_Status_Ticket_View";
	const PAGE_ADMIN_TYPE_TICKET                                        = "Page_Admin_Type_Ticket";
	const PAGE_ADMIN_TYPE_TICKET_LIST                                   = "Page_Admin_Type_Ticket_List";
	const PAGE_ADMIN_TYPE_TICKET_REGISTER                               = "Page_Admin_Type_Ticket_Register";
	const PAGE_ADMIN_TYPE_TICKET_SELECT                                 = "Page_Admin_Type_Ticket_Select";
	const PAGE_ADMIN_TYPE_TICKET_UPDATE                                 = "Page_Admin_Type_Ticket_Update";
	const PAGE_ADMIN_TYPE_TICKET_VIEW                                   = "Page_Admin_Type_Ticket_View";
	const PAGE_ADMIN_TYPE_TICKET_VIEW_LIST_USERS                        = "Page_Admin_Type_Ticket_View_List_Users";
	const PAGE_ADMIN_TYPE_USER                                          = "Page_Admin_Type_User";
	const PAGE_ADMIN_TYPE_USER_LIST                                     = "Page_Admin_Type_User_List";
	const PAGE_ADMIN_TYPE_USER_REGISTER                                 = "Page_Admin_Type_User_Register";
	const PAGE_ADMIN_TYPE_USER_SELECT                                   = "Page_Admin_Type_User_Select";
	const PAGE_ADMIN_TYPE_USER_UPDATE                                   = "Page_Admin_Type_User_Update";
	const PAGE_ADMIN_TYPE_USER_VIEW                                     = "Page_Admin_Type_User_View";
	const PAGE_ADMIN_TYPE_USER_VIEW_USERS                               = "Page_Admin_Type_User_View_Users";
	const PAGE_ADMIN_USER                                               = "Page_Admin_User";
	const PAGE_ADMIN_USER_CHANGE_ASSOC_USER_CORPORATION                 = "Page_Admin_User_Change_Assoc_User_Corporation";
	const PAGE_ADMIN_USER_CHANGE_CORPORATION                            = "Page_Admin_User_Change_Corporation";
	const PAGE_ADMIN_USER_CHANGE_USER_TYPE                              = "Page_Admin_User_Change_User_Type";
	const PAGE_ADMIN_USER_LIST                                          = "Page_Admin_User_List";
	const PAGE_ADMIN_USER_REGISTER                                      = "Page_Admin_User_Register";
	const PAGE_ADMIN_USER_SELECT                                        = "Page_Admin_User_Select";
	const PAGE_ADMIN_USER_UPDATE                                        = "Page_Admin_User_Update";
	const PAGE_ADMIN_USER_VIEW                                          = "Page_Admin_User_View";
	const PAGE_CONTACT                                                  = "Page_Contact";
	const PAGE_CORPORATION                                              = "Page_Corporation";
	const PAGE_HOME                                                     = "Page_Home";
	const PAGE_INSTALL                                                  = "Page_Install";
	const PAGE_LOGIN                                                    = "Page_Login";
	const PAGE_NOTIFICATION                                             = "Page_Notification";
	const PAGE_NOTIFICATION_List                                        = "Page_Notification_List";
	const PAGE_NOTIFICATION_VIEW                                        = "Page_Notification_View";
	const PAGE_PASSWORD_RECOVERY                                        = "Page_Password_Recovery";
	const PAGE_PASSWORD_RESET                                           = "Page_Password_Reset";
	const PAGE_NOT_CONFIRMED                                            = "Page_Not_Confirmed";
	const PAGE_NOT_FOUND                                                = "Page_Not_Found";
	const PAGE_NOT_LOGGED_IN                                            = "Page_Not_Logged_In";
	const PAGE_REGISTER                                                 = "Page_Register";
	const PAGE_REGISTER_CONFIRMATION                                    = "Page_Register_Confirmation";
	const PAGE_RESEND_CONFIRMATION_LINK                                 = "Page_Resend_Confirmation_Link";
	const PAGE_TEAM                                                     = "Page_Team";
	const PAGE_TEAM_INVITE_USER                                         = "Page_Team_Invite";
	const PAGE_TEAM_LIST                                                = "Page_Team_List";
	const PAGE_TEAM_REGISTER                                            = "Page_Team_Register";
	const PAGE_TEAM_SELECT                                              = "Page_Team_Select";
	const PAGE_TEAM_UPDATE                                              = "Page_Team_Update";
	const PAGE_TEAM_VIEW                                                = "Page_Team_View";
	const PATH_BODY_PAGE                                                = "Html/BodyPage/Body";
	const PATH_FOOTER                                                   = "Html/Footer/Footer.php";
	const PATH_FORM                                                     = "Html/Form/Form";
	const PATH_HEAD                                                     = "Html/Head/";
	const PATH_HEADER                                                   = "Html/Header/Header";
	const POST_BACK_FORM                                                = "HiddenTextForm";
	const RETURN_ERROR                                                  = "ReturnError";
	const RETURN_WARNING                                                = "ReturnWarning";
	const SESS_ADMIN_CORPORATION                                        = "SessionAdminCorporation";
	const SESS_ADMIN_DEPARTMENT                                         = "SessionAdminDepartment";
	const SESS_ADMIN_NOTIFICATION                                       = "SessionAdminNotification";
	const SESS_ADMIN_SYSTEM_CONFIGURATION                               = "SessionAdminSystemConfiguration";
	const SESS_ADMIN_TEAM                                               = "SessionAdminTeam";
	const SESS_ADMIN_TICKET                                             = "SessionAdminTicket";
	const SESS_ADMIN_TYPE_ASSOC_USER_TEAM                               = "SessionAdminTypeAssocUserTeam";
	const SESS_ADMIN_TYPE_STATUS_TICKET                                 = "SessionAdminTypeStatusTicket";
	const SESS_ADMIN_TYPE_TICKET                                        = "SessionAdminTypeTicket";
	const SESS_ADMIN_TYPE_USER                                          = "SessionAdminTypeUser";
	const SESS_ADMIN_USER                                               = "SessionAdminUser";
	const SESS_CONTACT_EMAIL                                            = "SessionContactEmail";
	const SESS_DEBUG                                                    = "SessionDebug";
	const SESS_DEVICE_LAYOUT                                            = "SessionDeviceLayout";
	const SESS_LAST_ACTIVITY                                            = "SessionLastActivity";
	const SESS_LANGUAGE                                                 = "SessionLanguage";
	const SESS_LOGIN_TWO_STEP_VERIFICATION                              = "SessionLoginTwoStepVerification";
	const SESS_PAGE_SACK                                                = "SessionPageStack";
	const SESS_PAGE_STACK_NUMBER                                        = "SessionPageStackNumber";
	const SESS_PASSWORD_RECOVERY                                        = "SessionPasswordRecovery";
	const SESS_UNLIMITED                                                = "SessionUnlimited";
	const SESS_USER                                                     = "SessionUser";
	const TABLE_ASSOC_TICKET_USER_REQUESTING                            = "ASSOC_TICKET_USER_REQUESTING";
	const TABLE_ASSOC_TICKET_USER_REQUESTING_FIELD_USER_BOND            = "AssocTicketUserRequestingUserBond";
	const TABLE_ASSOC_TICKET_USER_REQUESTING_FIELD_USER_EMAIL           = "AssocTicketUserRequestingUserEmail"; 
	const TABLE_ASSOC_TICKET_USER_REQUESTING_FIELD_TICKET_ID            = "AssocTicketUserRequestingTicketId";
	const TABLE_ASSOC_TICKET_USER_RESPONSIBLE                           = "ASSOC_TICKET_USER_RESPONSIBLE";
	const TABLE_ASSOC_TICKET_USER_RESPONSIBLE_FIELD_USER_EMAIL          = "AssocTicketUserResponsibleUserEmail";
	const TABLE_ASSOC_TICKET_USER_RESPONSIBLE_FIELD_TICKET_ID           = "AssocTicketUserResponsibleTicketId";
	const TABLE_ASSOC_USER_CORPORATION                                  = "ASSOC_USER_CORPORATION";
	const TABLE_ASSOC_USER_CORPORATION_FIELD_CORPORATION_NAME           = "AssocUserCorporationCorporationName";
	const TABLE_ASSOC_USER_CORPORATION_FIELD_DEPARTMENT_NAME            = "AssocUserCorporationDepartmentName";
	const TABLE_ASSOC_USER_CORPORATION_FIELD_REGISTRATION_DATE          = "AssocUserCorporationRegistrationDate";
	const TABLE_ASSOC_USER_CORPORATION_FIELD_REGISTRATION_ID            = "AssocUserCorporationRegistrationId";
	const TABLE_ASSOC_USER_CORPORATION_FIELD_USER_EMAIL                 = "AssocUserCorporationUserEmail";
	const TABLE_ASSOC_USER_TEAM                                         = "ASSOC_USER_TEAM";
	const TABLE_ASSOC_USER_TEAM_FIELD_TEAM_ID                           = "AssocUserTeamTeamId";
	const TABLE_ASSOC_USER_TEAM_FIELD_USER_EMAIL                        = "AssocUserTeamUserEmail";
	const TABLE_ASSOC_USER_TEAM_FIELD_USER_TYPE                         = "AssocUserTeamUserType";
	const TABLE_SYSTEM_CONFIGURATION                                    = "SYSTEM_CONFIGURATION";
	const TABLE_SYSTEM_CONFIGURATION_FIELD_OPTION_ACTIVE                = "SystemConfigurationOptionActive";
	const TABLE_SYSTEM_CONFIGURATION_FIELD_OPTION_DESCRIPTION           = "SystemConfigurationOptionDescription";
	const TABLE_SYSTEM_CONFIGURATION_FIELD_OPTION_NAME                  = "SystemConfigurationOptionName";
	const TABLE_SYSTEM_CONFIGURATION_FIELD_OPTION_NUMBER                = "SystemConfigurationOptionNumber";
	const TABLE_SYSTEM_CONFIGURATION_FIELD_OPTION_VALUE                 = "SystemConfigurationOptionValue";
	const TABLE_SYSTEM_CONFIGURATION_FIELD_OPTION_VALUE_DISABLE         = "SystemConfigurationOptionValueDisable";
	const TABLE_SYSTEM_CONFIGURATION_FIELD_OPTION_VALUE_ENABLE          = "SystemConfigurationOptionValueEnable";
	const TABLE_CORPORATION                                             = "CORPORATION";
	const TABLE_CORPORATION_FIELD_ACTIVE                                = "CorporationActive";
	const TABLE_CORPORATION_FIELD_NAME                                  = "CorporationName";
	const TABLE_COUNTRY                                                 = "COUNTRY";
	const TABLE_COUNTRY_FIELD_NAME                                      = "CountryName";
	const TABLE_COUNTRY_FIELD_ABBREVIATION                              = "CountryAbbreviation";
	const TABLE_COUNTRY_FIELD_REGION_CODE                               = "CountryRegionCode";
	const TABLE_FIELD_REGISTER_DATE                                     = "RegisterDate";
	const TABLE_DEPARTMENT                                              = "DEPARTMENT";
	const TABLE_DEPARTMENT_FIELD_CORPORATION                            = "DepartmentCorporation";
	const TABLE_DEPARTMENT_FIELD_INITIALS                               = "DepartmentInitials";
	const TABLE_DEPARTMENT_FIELD_NAME                                   = "DepartmentName";
	const TABLE_HISTORY_TICKET                                          = "HISTORY_TICKET";
	const TABLE_HISTORY_TICKET_FIELD_DESCRIPTION                        = "HistoryTicketDescription";
	const TABLE_HISTORY_TICKET_FIELD_ID                                 = "HistoryTicketId";
	const TABLE_HISTORY_TICKET_FIELD_STATUS                             = "HistoryTicketStatus";
	const TABLE_HISTORY_TICKET_FIELD_USER_EMAIL                         = "UserEmail";
	const TABLE_HISTORY_TICKET_FIELD_SUGGESTION                         = "Suggestion";
	const TABLE_HISTORY_TICKET_FIELD_TICKET_ID                          = "TicketId";
	const TABLE_NOTIFICATION                                            = "NOTIFICATION";
	const TABLE_NOTIFICATION_FIELD_ACTIVE                               = "NotificationActive";
	const TABLE_NOTIFICATION_FIELD_ID                                   = "NotificationId";
	const TABLE_NOTIFICATION_FIELD_TEXT                                 = "NotificationText";
	const TABLE_TEAM                                                    = "TEAM";
	const TABLE_TEAM_FIELD_TEAM_DESCRIPTION                             = "TeamDescription";
	const TABLE_TEAM_FIELD_TEAM_ID                                      = "TeamId";
	const TABLE_TEAM_FIELD_TEAM_NAME                                    = "TeamName";
	const TABLE_TICKET                                                  = "TICKET";
	const TABLE_TICKET_FIELD_TICKET_DESCRIPTION                         = "TicketDescription";
	const TABLE_TICKET_FIELD_TICKET_ID                                  = "TicketId";
	const TABLE_TICKET_FIELD_TICKET_STATUS                              = "TicketStatus";
	const TABLE_TICKET_FIELD_TICKET_SUGGESTION                          = "TicketSuggestion";
	const TABLE_TICKET_FIELD_TICKET_TITLE                               = "TicketTitle";
	const TABLE_TICKET_FIELD_TICKET_TYPE                                = "TicketType";
	const TABLE_TYPE_ASSOC_USER_REQUESTING                              = "TYPE_ASSOC_USER_REQUESTING";
	const TABLE_TYPE_ASSOC_USER_REQUESTING_FIELD_TYPE_BOND              = "TypeAssocUserRequestingTypeBond";
	const TABLE_TYPE_ASSOC_USER_TEAM                                    = "TYPE_ASSOC_USER_TEAM";
	const TABLE_TYPE_ASSOC_USER_TEAM_FIELD_DESCRIPTION                  = "TypeAssocUserTeamDescription";
	const TABLE_TYPE_STATUS_TICKET                                      = "TYPE_STATUS_TICKET";
	const TABLE_TYPE_STATUS_TICKET_FIELD_DESCRIPTION                    = "TypeStatusTicketDescription";
	const TABLE_TYPE_TICKET                                             = "TYPE_TICKET";
	const TABLE_TYPE_TICKET_FIELD_DESCRIPTION                           = "TypeTicketDescription";
	const TABLE_TYPE_USER                                               = "TYPE_USER";
	const TABLE_TYPE_USER_FIELD_DESCRIPTION                             = "TypeUserDescription";
	const TABLE_USER                                                    = "USER";
	const TABLE_USER_FIELD_BIRTH_DATE                                   = "BirthDate";
	const TABLE_USER_FIELD_CORPORATION                                  = "Corporation";
	const TABLE_USER_FIELD_COUNTRY                                      = "Country";
	const TABLE_USER_FIELD_EMAIL                                        = "Email";
	const TABLE_USER_FIELD_GENDER                                       = "Gender";
	const TABLE_USER_FIELD_HASH_CODE                                    = "HashCode";
	const TABLE_USER_FIELD_NAME                                         = "Name";
	const TABLE_USER_FIELD_PASSWORD                                     = "Password";
	const TABLE_USER_FIELD_REGION                                       = "Region";
	const TABLE_USER_FIELD_SESSION_EXPIRES                              = "SessionExpires";
	const TABLE_USER_FIELD_TWO_STEP_VERIFICATION                        = "TwoStepVerification";
	const TABLE_USER_FIELD_USER_ACTIVE                                  = "UserActive";
	const TABLE_USER_FIELD_USER_CONFIRMED                               = "UserConfirmed";
	const TABLE_USER_FIELD_USER_PHONE_PRIMARY                           = "UserPhonePrimary";
	const TABLE_USER_FIELD_USER_PHONE_PRIMARY_PREFIX                    = "UserPhonePrimaryPrefix";
	const TABLE_USER_FIELD_USER_PHONE_SECONDARY                         = "UserPhoneSecondary";
	const TABLE_USER_FIELD_USER_PHONE_SECONDARY_PREFIX                  = "UserPhoneSecondaryPrefix";
	const TABLE_USER_FIELD_TYPE                                         = "UserType";
	const TABLE_USER_FIELD_USER_UNIQUE_ID                               = "UserUniqueID";
	const TYPE_USER_DEFAULT                                             = "USER";
	const TYPE_USER_SUPER                                               = "SUPER_ADMINISTRATOR";
	const USER_ACTIVE                                                   = 1;
	const USER_NOT_CONFIRMED                                            = "USER_NOT_CONFIRMED";
	const USER_NOT_LOGGED_IN                                            = "UserNotLoggedIn";
	
	/* Instances */
	protected static $Instance;
	protected        $Factory = NULL;
	public           $Session = NULL;
	
	/* Propriedades de Classe */
	public $DefaultApplicationAddress        = NULL;
	public $DefaultApplicationName           = "Base";
	public $DefaultGoogleMapsApiKey          = NULL;
	public $DefaultEmailNoReplyFormAddress   = NULL;
	public $DefaultEmailNoReplyFormPassword  = NULL;
	public $DefaultEmailSupportFormAddress   = NULL;
	public $DefaultLanguage                  = NULL;
	public $DefaultLogPath                   = NULL;
	public $DefaultMySqlAddress              = NULL;
	public $DefaultMySqlDataBase             = NULL;
	public $DefaultMySqlPort                 = NULL;
	public $DefaultMySqlImportUser           = NULL;
	public $DefaultMySqlImportUserPassword   = NULL;
	public $DefaultMySqlSuperUser            = NULL;
	public $DefaultMySqlSuperUserPassword    = NULL;
	public $DefaultMySqlUser                 = NULL;
	public $DefaultMySqlUserPassword         = NULL;
	public $DefaultServerFile                = NULL;
	public $DefaultServerImage               = NULL;
	public $DefaultServerJavaScript          = NULL;
	public $EnableLogMySqlQuery              = FALSE;
	public $EnableLogMySqlError              = FALSE;
	public $SessionTime                      = 3600;
	
	/* Linguas Habilitadas / Desabilitadas */
	public $LanguageEnglishEnabled       = TRUE;
	public $LanguageGermanEnabled        = FALSE;
	public $LanguagePortugueseEnabled    = TRUE;
	public $LanguageSpanishEnabled       = FALSE;
	
	/**                               **/
	/************* METODOS *************/
	/**                               **/
	
	/* Clone */
	protected function __clone()
    {
        exit(get_class($this) . ": Error! Clone Not Allowed!");
    }
	
	/* Constructor */
	protected function __construct() 
    {
		if($this->Factory == NULL)
			$this->Factory = Factory::__create();
    }
	
	/* Singleton */
	public static function __create()
    {
        if (!isset(self::$Instance)) 
		{
            $class = __CLASS__;
            self::$Instance = new $class;
			if(self::$Instance->SetApplication() == Config::RETURN_WARNING)
				echo '<script type="text/javascript">alert("A sessão terminou devido ao tempo inativo!");</script>';
        }
        return self::$Instance;
    }
	
	public static function GetDefaultLanguageByDir($PageDirName)
	{
		if (strpos($PageDirName, str_replace('Language/', '', Config::LANGUAGE_GERMAN)) !== false) 
			return Config::LANGUAGE_GERMAN;
		elseif (strpos($PageDirName, str_replace('Language/', '', Config::LANGUAGE_ENGLISH)) !== false) 
			return Config::LANGUAGE_ENGLISH;
		elseif (strpos($PageDirName, str_replace('Language/', '', Config::LANGUAGE_SPANISH)) !== false) 
			return Config::LANGUAGE_SPANISH;
		elseif (strpos($PageDirName, str_replace('Language/', '', Config::LANGUAGE_PORTUGUESE)) !== false)
			return Config::LANGUAGE_PORTUGUESE;
		else return Config::RETURN_ERROR;
	}
	
	public static function GetPageConstant($Constant)
	{
		if(defined("Config::" . strtoupper(implode(preg_split('/(?=[A-Z])/', $Constant, -1, PREG_SPLIT_NO_EMPTY), "_"))))
			return constant("Config::" . strtoupper(implode(preg_split('/(?=[A-Z])/', $Constant, -1, PREG_SPLIT_NO_EMPTY), "_")));
		else return Config::RETURN_ERROR;
	}
	
	public function SetApplication()
	{
		if(class_exists("ProjectConfig"))
		{
			error_reporting(E_ALL);
			date_default_timezone_set(ProjectConfig::$TimeZone);
			setlocale(LC_ALL, 'UTF8');
			if(ini_set("display_errors", ProjectConfig::$DisplayErrors) === FALSE)
				exit(Config::INI_SET_FATAL_ERROR_DISPLAY_ERRORS);
			if(ini_set("session.save_path", ProjectConfig::$SessionFolder) === FALSE)
				exit(Config::INI_SET_FATAL_ERROR_SESSION_SAVE_PATH);
			if(strcmp("On", ProjectConfig::$EnableUpload) == 0)
			{
				if(!file_exists(ProjectConfig::$UploadDirectory))
					mkdir(ProjectConfig::$UploadDirectory, 0755, TRUE);
				if(!file_exists(ProjectConfig::$HtaccessFile))
				{
					$htaccessFile = fopen(ProjectConfig::$HtaccessFile, 'w') or die(Config::HTACCESS_ERROR_FILE_CREATE);
					fwrite($htaccessFile, "php_value  file_uploads " . ProjectConfig::$EnableUpload . "\n");
					fwrite($htaccessFile, "php_value  max_file_uploads " . ProjectConfig::$UploadFileLimit . "\n");
					fwrite($htaccessFile, "php_value  upload_max_filesize " . ProjectConfig::$UploadFileMaxSize . "\n");
					fwrite($htaccessFile, "php_value  post_max_size " . ProjectConfig::$UploadFileMaxSize . "\n");
					fclose($htaccessFile);
				}
			}
			$this->Session = $this->Factory->CreateSession();
			$this->DefaultApplicationAddress             = ProjectConfig::$AddressApplication;
			$this->DefaultApplicationName                = ProjectConfig::$ApplicationName;
			$this->DefaultMySqlAddress                   = ProjectConfig::$MySqlDataBaseAddress;
			$this->DefaultMySqlPort                      = ProjectConfig::$MySqlDataBasePort;
			$this->DefaultMySqlDataBase                  = ProjectConfig::$MySqlDataBaseName;
			$this->DefaultMySqlImportUser                = ProjectConfig::$MysqlDataBaseImportUser;
			$this->DefaultMySqlImportUserPassword        = ProjectConfig::$MysqlDataBaseImportUserPassword;
			$this->DefaultMySqlSuperUser                 = ProjectConfig::$MySqlDataBaseSuperUser;
			$this->DefaultMySqlSuperUserPassword         = ProjectConfig::$MySqlDataBaseSuperUserPassword;
			$this->DefaultMySqlUser                      = ProjectConfig::$MySqlDataBaseUser;
			$this->DefaultMySqlUserPassword              = ProjectConfig::$MySqlDataBaseUserPassword;
			$this->DefaultServerFile                     = ProjectConfig::$AddressFileServer;
			$this->DefaultServerImage                    = ProjectConfig::$AddressImageServer;
			$this->DefaultServerJavaScript               = ProjectConfig::$AddressJavaScriptServer;
			$this->DefaultEmailNoReplyFormAddress        = ProjectConfig::$EmailNoReplyAccount;
			$this->DefaultEmailNoReplyFormAddressReplyTo = ProjectConfig::$EmailNoReplyAccountReplyTo;
			$this->DefaultEmailNoReplyFormPassword       = ProjectConfig::$EmailNoReplyPassword;
			$this->DefaultEmailSupportFormAddress        = ProjectConfig::$EmailSupportAccount;
			$this->DefaultGoogleMapsApiKey               = ProjectConfig::$GoogleMapsApiKey;
			$this->DefaultLanguage                       = ProjectConfig::$DefaultLanguage;
			$this->DefaultLogPath                        = ProjectConfig::$LogFolder;
			$this->Session->CreateBasic($this->DefaultApplicationName, $this->SessionTime);
			return $this->Session->CheckActivity(self::SESS_LAST_ACTIVITY, self::SESS_USER, 
												 $this->SessionTime, self::SESS_UNLIMITED);
			
		}
		else exit ("Config: Project Config Class Not found");
	}
}
?>